project_id = "vbrhjptkfwugeheqmvlz"

[functions.calculate-numerology]
verify_jwt = false

[functions.generate-map]
verify_jwt = false

[functions.gerar-pdf]
verify_jwt = false

[functions.generate-gamma-pdf]
verify_jwt = false

[functions.webhook-demo]
verify_jwt = false

[functions.seed-admin]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.ensure-profile]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.update-numerology-content]
verify_jwt = false