import "https://deno.land/x/xhr@0.1.0/mod.ts";
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.57.4';

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    console.log('🚀 Iniciando atualização COMPLETA de conteúdo numerológico...');

    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    console.log('🗑️ Limpando base existente...');
    await supabase.from('numerology_texts').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('cabalistic_angels').delete().neq('id', '00000000-0000-0000-0000-000000000000');

    // Textos COMPLETOS extraídos do PDF - versão integral
    const allTexts = [
      // MOTIVAÇÃO (1-22)
      { section: 'motivacao', key_number: 1, title: 'Motivação 1', body: `Deseja Independência – Liberdade, liderança e controle de tudo; viver longe de pressões, ser campeão (ã) absoluto (a), realizar-se em si mesmo (a); ficar longe da mediocridade, fazer fortuna, ser elogiado (a) e atendido (a) pelo mundo; viver longe de detalhes; impor seus padrões pessoais; muito dinamismo e autossuficiência; não ser atrapalhado (a) por ninguém, ficar só.\n\nO Número 1 na Motivação exige que você se situe sempre de forma a ficar na frente dos outros. Tem que ser o (a) primeiro (a) em tudo o que faz. O fato de ser o (a) primeiro (a) o (a) impede, obviamente, de ter muita consideração pelos outros até que suas próprias necessidades sejam satisfeitas. A liderança adquirida em vidas passadas traz agora o desejo de continuar a se empenhar numa consciência mais elevada. Torna-se independente, também, com relação às suas crenças. O desejo por pensamentos livres e independentes continua ocupando o seu anseio mais profundo. Ambicioso (a) e criativo (a), é direto (a) e não gosta de muitos detalhes, quer liderar, dirigir, dominar; às vezes é obstinado (a). Não gosta muito de receber ordens de quem quer que seja e trabalha melhor por conta própria ou em cargo de chefia. A incompreensão e a recusa em aceitar conselhos podem trazer transtornos à sua carreira e aos seus planos profissionais. Se não tiver bom nível de consciência espiritual, poderá se tornar egoísta, excessivamente vaidoso (a) e arrogante. Geralmente é impaciente e com pouco senso diplomático. Por esse motivo poderá enfrentar dificuldades no seu meio profissional ou mesmo entre familiares, amigos e companheiros afetivos. Suas boas qualidades são: confiança em si, distinção, poder executivo, dignidade e foco nos propósitos.\n\nQuando inseguro (a) tende a ameaçar os outros, podendo agredir, ofender, se tornar inflexível, irredutível, vingativo (a) e preconceituoso (a). Cultura, educação e refinamento pessoal são características indispensáveis que precisa adquirir para o seu triunfo pessoal, profissional e principalmente afetivo.` },

      { section: 'motivacao', key_number: 2, title: 'Motivação 2', body: `Deseja Paz e Equilíbrio - Prestar serviço e devoção; criar harmonia, sentir o ritmo da vida, trabalhar com os outros, ter amigos leais e boas companhias; acumular conhecimentos e coisas; conforto sem supérfluos; ser amado (a) por todos, receber convites, sentir-se compreendido (a); vencer todas as negociações; não ser exposto (a).\n\nO Número 2 na Motivação indica o desejo de ser sempre gentil com todos, conseguindo ou não. Deseja ser compassivo (a), compreensivo (a), atencioso (a), útil e sempre fazendo concessões em favor da harmonia de todos. O seu maior desejo é a paz e a harmonia. O discernimento é um ponto forte do seu caráter; por esse motivo é um (a) bom (a) intermediário (a) ajudando a levar a paz às forças opostas. Anseia por amor e compreensão e prefere ser liderado (a) a liderar. O seu desejo é estar casado (a); desfrutar de companheirismo, paz, harmonia e conforto. Manifesta a sua natureza sensível através da suavidade, cordialidade e prestatividade; a sua principal característica é a cooperação. Pela sua passividade e calma natural, normalmente as pessoas com quem convive tendem a se aproveitar e explorá-lo (a). Normalmente não procura impor suas ideias; prefere escutar os outros antes de expor as suas próprias. Está sempre procurando reunir conhecimentos sobre assuntos diversos e se relaciona com todas as pessoas sem discriminar raça, credo, classe social ou posição econômica; numa só amizade e dedicação. É muito vulnerável em sua sensibilidade e se magoa profundamente com fatos que a outros não afetariam.\n\nQuando inseguro (a) tende a não decidir, escapa, elogia demais os outros, deixa-se influenciar, chora, enfraquece, fica longe das atenções, se deprime, critica e ironiza. É importante para o seu desenvolvimento profissional e pessoal, que aprenda a conviver com as pessoas; ser mais comunicativo (a) e compartilhar os seus conhecimentos com todos, levando sua mensagem de harmonia e paz.` },

      { section: 'motivacao', key_number: 3, title: 'Motivação 3', body: `Deseja a Beleza em Todas as Coisas - Plateia; ser o centro de todas as atenções; interesses múltiplos, estar sempre ocupado (a); esquecer o desagradável; numerosas amizades, namorar tudo e todas (os), estar cercado (a) por uma atmosfera agradável, ser amado (a), estar com gente bonita; sentimentos intensos e extremados; divertir-se; vender ideias, se autopromover; realizar todas as fantasias; comprar compulsivamente.\n\nO Número 3 na Motivação indica que o seu maior desejo é se expressar e receber a aprovação dos outros. Quer emitir a sua opinião, ser criativo (a), cultivar o talento e admirar a beleza. Como instrumento para a sua expressão efetiva, acredita na abordagem vitrine em relação à vida. Quer explorar o aqui e agora e não o passado ou futuro. Procura a felicidade e a encontra ao deixar os outros felizes. É muito otimista, alegre, sociável e tem grande facilidade para se comunicar. Possui talento natural para as artes, literatura, música ou teatro. Gosta de estar sempre rodeado de pessoas e ser o centro das atenções. Tem tendência a dispersar suas energias em muitas atividades diferentes. Pode ser superficial em seus relacionamentos e ter dificuldade para focar em projetos de longo prazo. Quando em desequilíbrio, pode se tornar fofoqueiro, exibicionista ou crítico destrutivo.` },

      { section: 'motivacao', key_number: 4, title: 'Motivação 4', body: `Deseja Ordem em Todas as Coisas – Fidelidade absoluta; persistência, disciplina rígida; conquistas materiais; rígido código de ética, viver longe da pretensão e falsidade; anseia amor, repele as atenções emocionais; viver ao ar livre, muita saúde, limpeza e arrumação; o máximo de segurança, ser rico (a) e não precisar de ninguém; comprar tudo o que deseja sem ficar descapitalizado.\n\nO Número 4 na Motivação mostra o desejo de ver os fatos reais e a verdade sem enfeites, o que o (a) torna mais preparado (a) que a maioria para realizar algo construtivo com isso. Muitas pessoas pedem a verdade, mas poucas estão tão preparadas como você para aceitá-la. O seu desejo é ser justo (a) em todos os seus relacionamentos; gosta de trabalhar duro por aquilo que ambiciona; priva-se até mesmo de alguma coisa ou aceita inconveniências em favor de vantagens futuras. O lado prático permeia todo o seu ser; seu desejo é ver tudo muito bem organizado. Deseja ordem e disciplina tanto em casa como no trabalho. Quer trabalhar metodicamente e com afinco em favor dos outros e não gosta muito de inovações. É um (a) conservador (a) nato (a), realista e equilibrado (a), e sempre é possível contar com você. Profissional de alto gabarito se realiza na dedicação, na perfeição dos detalhes e na conclusão de um trabalho bem feito. Ama o sólido, o palpável, o prático, aquilo que se desenvolve, cresce e que protege. Gosta de se sentir protegido (a) e assessorado (a). Normalmente é prático (a), analítico (a) e confiável; valoriza a lealdade e a honestidade. É bom (a) disciplinador (a), determinado (a) e tenaz em seus propósitos. Possui habilidades mecânicas naturais e trabalha bem com as mãos. É extremamente otimista e enfrenta os obstáculos com coragem, por mais árduos que sejam.\n\nQuando inseguro (a) tende a se tornar rígido (a), guarda ou acumula coisas para o futuro, toma todas as precauções possíveis, se queixa e se subestima; teima, fica obsessivo (a) e pessimista; controla tudo e todos. As suas conquistas materiais devem ser através dos seus talentos profissionais e esforços permanentes; assim pode conseguir tudo o que deseja, mas tenha também objetivos que visem beneficiar a humanidade.` },

      { section: 'motivacao', key_number: 5, title: 'Motivação 5', body: `Deseja Liberdade Pessoal – Mudanças constantes; falar, agir, viajar, despreocupação, variedade, distância da rotina e dos detalhes; abertura a qualquer experiência; eterna tentativa; passar adiante, abandonar com facilidade ou agarrar-se demasiado tempo; pessoas novas e bonitas; evitar caminhos já percorridos, buscar o inusitado e o novo; ter todas as gratificações sensuais que preferir; exibir qualidades, tirar o máximo da vida, ser amado sem sentir-se preso; não usar relógio.\n\nO Número 5 na Motivação indica um forte desejo de buscar até finalmente encontrar as soluções nas quais os outros nunca pensaram antes. Está sempre alerta e suscetível a tudo o que está relacionado com os cinco sentidos. Aborda tudo com certa intensidade sexual. Tudo o que parece ser diferente e interessante chama a sua atenção. A variedade da autoexpressão é absolutamente essencial. As viagens são um dos desejos da sua alma, por considerá-las educativas e ampliadoras do seu horizonte. É um ser mutável; gosta de variedades e de experiências incomuns, e está sempre à procura de novas oportunidades. Possui natureza perceptiva, arguta, perspicaz e curiosidade natural. Isso instiga o seu desejo de investigar e elucidar qualquer situação ou problema. Gosta de novidades e é um (a) entusiasta por novas experiências e novos encontros; às vezes gosta também de rupturas. Com seu raciocínio rápido se adapta a qualquer situação, sentindo-se à vontade e fazendo com que os outros também se sintam. Relaciona-se bem em sociedade; possui grande versatilidade e talentos para se dar bem em várias e diferentes atividades, e não se cansa nem se atrapalha, pois como normalmente só faz o que gosta, é do tipo que trabalha descansando.` },

      { section: 'motivacao', key_number: 6, title: 'Motivação 6', body: `Deseja um Lar Feliz – Família, união, harmonia, luxo e conforto; tolerância em relação aos outros; dar refúgio e proteção aos que precisam de auxílio; solidariedade, sentir o ritmo da vida; sentimentalismo exagerado; que todos sigam suas ideias; dar jeito em tudo e solucionar tudo para todos; trabalhar em equipe; tem interesse em tudo e por todos; distância de trabalhos mecânicos; sentir-se amado (a) e necessário (a), tornar-se insubstituível, que seus filhos só deem alegrias; não precisar pedir favores.\n\nO Número 6 na Motivação descreve um grande desejo de ser amistoso (a), afável, e conscientemente interessado (a) nos problemas dos outros como se fossem os seus. Deseja se envolver, assumir um senso de responsabilidade social, e até mesmo compartilhar de um senso de culpa coletiva pelo que os outros fazem em cooperação de grupo. O seu desejo é ensinar aos outros a manterem a paz e a harmonia em suas vidas. O seu interesse pelo bem estar dos seus familiares é tão profundo que às vezes se torna sufocante e priva que eles vivam as suas próprias experiências. Age de modo convencional e tolerante em relação ao comportamento dos outros. Deseja ser sempre o refugio e o abrigo para aqueles que precisam de atenção e auxilio. Sente o ritmo da vida na harmonia da música. Às vezes se torna um (a) sentimentalista exagerado (a) incapaz de um julgamento real de uma situação. Deseja impor suas próprias ideias e princípios a todos. Presta favores de boa vontade. Gosta de cozinhar e aprecia uma boa mesa. Não se sente atraído (a) por trabalhos mecânicos e técnicos. É idealista e tem como princípio orientar e consertar tudo o que está errado no mundo. Quer criar raízes e fazer com que sua vida gire em torno do seu lar e das pessoas queridas.\n\nQuando inseguro (a) tende a mesquinharia, sentimentalismo, apego à família ou ao passado, manipulação, perda de confiança e fé, atrai relações complicadas. Por sua tendência à vaidade e ao egoísmo, é bom que se dedique aos estudos esotéricos, metafísicos e espiritualistas, e seja compreensivo (a) com os outros.` },

      { section: 'motivacao', key_number: 7, title: 'Motivação 7', body: `Deseja Obter Vitórias Intelectuais – Boa educação; privacidade, paz, sossego, silêncio; estar só, atrair sem forçar nada, analisar profundamente; reservado (a), intelectual, filósofo (a), tímido (a) em público; profundamente emotivo (a), mas não demonstra os sentimentos; viver longe da pretensão e falsidade; proteger-se da curiosidade dos outros a respeito de si; apreciar livros raros e tecidos finos; ter poucos amigos íntimos; sabedoria, refinamento; não se misturar, ser ouvido por todos.\n\nO Número 7 na Motivação mostra o seu desejo de ficar sozinho (a) para explorar as profundezas da alma. A sua busca é pela perfeição, de forma a se destacar, em seu próprio julgamento, como a última palavra em distinção profissional. Busca expressões de profundidade e percepção rara e não o que se comunica facilmente à pessoas comuns. Na verdade, a sua motivação por especialização tende a fazer com que não goste de pessoas comuns ou medíocres. Admira o refinamento, a exclusividade, a sabedoria, a autoridade especializada, a distinção única, a perfeição profissional, valores interiores, senso de espiritualidade, consciência de fé filosófica e reconhecimento da herança cultural. Possui intuição e percepção refinadas; com isso percebe ou vê o que para os outros ainda é imperceptível; pode vir a desenvolver alguma forma de contato com outras realidades não físicas. Mostra-se místico (a) e misterioso (a). Detesta ser mandado (a), não gosta de desconforto físico, de barulho e confusão. É observador (a), pesquisador (a) e quer descobrir o porquê de tudo. Não gosta de ter a liberdade tolhida, quer paz e tranquilidade para viver consigo mesmo (a); sonhar e meditar. É íntegro (a) e autossuficiente; possui senso de justiça. Deseja aprender sempre mais e entender de tudo. Está sempre em busca de mais sabedoria.\n\nQuando inseguro (a) tende a se isolar, emudecer; achar explicações filosóficas, psicológicas, espirituais, cármicas, e tenta explicar tudo racionalmente, dissecando, analisando, criticando com frieza e distância. Bebidas alcoólicas, cigarros e drogas em geral são venenos para o seu organismo; evite-os. Será muito mais feliz se viver próximo à água, seja de um rio, lago ou mar.` },

      { section: 'motivacao', key_number: 8, title: 'Motivação 8', body: `Deseja Poder Pessoal e Sucesso Financeiro – Domínio no mundo empresarial; liderança, força, determinação e faro para negócios; sucesso através da organização, eficiência e visão ampla; dinheiro e grandes ambições; ser respeitado (a) em seus valores; acumular bens materiais; distância de rotina e detalhes; justiça, honestidade e inspiração; conhecer pessoas profundamente; ter tudo em ordem e livrar-se das confusões com garra e coragem; vencer na profissão e na vida.\n\nO Número 8 na Motivação indica que você realmente aspira uma posição de poder e influência no mundo. Deseja tudo em grande escala. Geralmente tem facilidade para tomar decisões importantes, pois sabe o que quer em termos materiais e é capaz de avaliar com precisão pessoas e situações no que diz respeito às suas exigências. Deseja a prosperidade material e possui clara visão financeira. Aprecia a eficiência sob todas as formas e faz bom juízo de valores, particularmente em considerações importantes onde o dinheiro está envolvido. Possui a habilidade de organizar grandes grupos e empreendimentos com sucesso. Nasceu para o mundo dos grandes negócios e adora lutar contra seus opositores. Normalmente é ambicioso (a) e quer poder, riqueza e sucesso. Possui mente determinada e realizadora. Geralmente não luta contra os obstáculos, prefere contorná-los, e desse modo consegue transformar opositores em colaboradores. Não é precipitado (a), nem impulsivo (a), nem muito ousado (a), gosta de segurança e de reconhecimento dos seus feitos. É intelectual, analítico (a), equilibrado (a) e muito eficiente naquilo que se propõe a fazer. Possui tato, visão e imaginação para os negócios e geralmente é bem sucedido (a). O seu objetivo é o dinheiro, os bens materiais e o poder. Possui surpreendente força, coragem e energia que aplica em tudo o que faz, usando a capacidade, previsão, responsabilidade e prudência que lhe são características.` },

      { section: 'motivacao', key_number: 9, title: 'Motivação 9', body: `Deseja Servir a Humanidade - Contribuir para um mundo melhor; ajudar pessoas necessitadas; promover causas humanitárias; ser um exemplo de sabedoria e compaixão; transcender limitações pessoais; deixar um legado positivo para as gerações futuras.\n\nO Número 9 na Motivação indica uma pessoa movida pelo desejo de servir a humanidade e contribuir para um mundo melhor. Possui uma visão universal e grande compaixão pelos menos favorecidos. Tem necessidade de se envolver em causas humanitárias e de fazer a diferença na vida das pessoas. É sábio (a), tolerante e possui uma perspectiva ampla da vida. Valoriza a justiça social e a igualdade. Pode se sacrificar pelos outros e às vezes negligenciar suas próprias necessidades. Tem tendência a ser idealista e pode se frustrar quando a realidade não corresponde aos seus ideais. Quando em desequilíbrio, pode se tornar fanático (a), moralista ou depressivo (a). Suas principais qualidades são: compaixão, sabedoria, generosidade, idealismo e visão universal.` },

      { section: 'motivacao', key_number: 11, title: 'Motivação 11', body: `Deseja Inspiração e Iluminação - Inspirar outras pessoas através do exemplo; desenvolver dons psíquicos e intuitivos; ser um canal para energias superiores; promover a evolução espiritual da humanidade; viver de acordo com princípios elevados; ser uma luz no mundo.\n\nO Número 11 na Motivação representa uma pessoa com forte desejo de inspirar e iluminar outros. Possui intuição desenvolvida e capacidades psíquicas naturais. Busca constantemente a elevação espiritual e deseja ser um canal para energias superiores. É idealista, visionário e tem a capacidade de ver além das aparências. Sua missão é ajudar na evolução da consciência humana. Pode ser muito sensível e nervoso devido à alta vibração energética. Quando equilibrado, é uma fonte de inspiração e sabedoria para outros.` },

      { section: 'motivacao', key_number: 22, title: 'Motivação 22', body: `Deseja Construir para a Humanidade - Realizar grandes obras que beneficiem muitas pessoas; combinar visão espiritual com praticidade; ser um construtor de pontes entre o ideal e o real; deixar um legado duradouro; trabalhar em projetos de larga escala que transformem o mundo.\n\nO Número 22 na Motivação indica uma pessoa com o desejo de materializar grandes visões em benefício da humanidade. Combina a intuição do 11 com a praticidade do 4, sendo capaz de transformar sonhos em realidade. Possui uma visão ampla e a capacidade de organizar e executar projetos grandiosos. É um construtor nato, mas em escala universal. Sua motivação é deixar uma marca positiva e duradoura no mundo. Pode enfrentar grandes pressões devido às altas expectativas que tem de si mesmo.` },

      // IMPRESSÃO (1-22)
      { section: 'impressao', key_number: 1, title: 'Impressão 1', body: `As Pessoas o (a) Veem Como um (a) Líder - Independente, corajoso (a), criativo (a), inovador (a), original, autoconfiante, determinado (a), pioneiro (a), forte, direto (a), honesto (a), franco (a), impaciente, às vezes arrogante e egoísta.\n\nO Número 1 na Impressão significa que você normalmente causa uma primeira impressão de alguém que é independente e que não necessita de ninguém para chegar aonde quer. Parece ser uma pessoa que sabe liderar e dirigir os outros. Dá a impressão de ser alguém ambicioso (a), enérgico (a), pioneiro (a), original e inovador (a). As pessoas o (a) veem como um (a) líder nato (a), alguém que não gosta de receber ordens e que prefere dar as cartas. Pode parecer impaciente ou até mesmo arrogante para alguns, mas geralmente projeta uma imagem de força e determinação. Sua presença é marcante e você tende a se destacar em qualquer ambiente. As pessoas esperam que você tome iniciativas e assuma responsabilidades. Sua energia pioneira e sua capacidade de inovação são evidentes para todos que o conhecem.` },

      { section: 'impressao', key_number: 2, title: 'Impressão 2', body: `As Pessoas o (a) Veem Como Cooperativo (a) - Diplomático (a), gentil, prestativo (a), pacífico (a), harmonioso (a), sensível, tímido (a), modesto (a), discreto (a), colaborador (a), mediador (a), às vezes indeciso (a) ou passivo (a).\n\nO Número 2 na Impressão faz com que as pessoas o vejam como alguém cooperativo, diplomático e sensível. Você parece ser uma pessoa que valoriza a harmonia e a paz, preferindo trabalhar em equipe a liderar. Dá a impressão de ser gentil, prestativo e sempre disposto a ajudar os outros. As pessoas sentem que podem contar com você para mediar conflitos e encontrar soluções pacíficas. Pode parecer tímido ou modesto, mas projeta uma energia acolhedora e compreensiva. Sua capacidade de escutar e sua sensibilidade são evidentes, fazendo com que outros se sintam à vontade para compartilhar seus problemas. Às vezes pode dar a impressão de ser indeciso ou de não ter opinião própria, mas na verdade está sempre buscando o equilíbrio.` },

      { section: 'impressao', key_number: 3, title: 'Impressão 3', body: `As Pessoas o (a) Veem Como Comunicativo (a) - Criativo (a), artístico (a), expressivo (a), sociável, otimista, divertido (a), talentoso (a), carismático (a), inspirador (a), às vezes superficial ou disperso (a).\n\nO Número 3 na Impressão faz com que você seja visto como uma pessoa muito comunicativa, criativa e expressiva. As pessoas percebem sua facilidade para se comunicar e sua habilidade artística natural. Você projeta uma energia alegre, otimista e contagiante que atrai os outros. Dá a impressão de ser alguém talentoso, que tem facilidade com palavras, artes ou qualquer forma de expressão criativa. Sua presença ilumina o ambiente e as pessoas se sentem inspiradas e animadas ao seu redor. Pode parecer alguém que gosta de ser o centro das atenções e que tem muitos talentos diferentes. Às vezes pode dar a impressão de ser superficial ou de não levar as coisas muito a sério, mas na verdade possui uma capacidade natural de encontrar o lado positivo das situações.` },

      { section: 'impressao', key_number: 4, title: 'Impressão 4', body: `As Pessoas o (a) Veem Como Confiável - Prático (a), organizado (a), trabalhador (a), disciplinado (a), responsável, estável, leal, persistente, meticuloso (a), às vezes rígido (a) ou teimoso (a).\n\nO Número 4 na Impressão faz com que as pessoas o vejam como alguém extremamente confiável e prático. Você projeta uma imagem de estabilidade, organização e responsabilidade. As pessoas sentem que podem contar com você para realizar tarefas importantes e cumprir compromissos. Dá a impressão de ser alguém disciplinado, trabalhador e que não tem medo de trabalho duro. Sua ética de trabalho é evidente e você parece ser alguém que valoriza a tradição e os métodos comprovados. Pode dar a impressão de ser conservador ou resistente a mudanças, mas na verdade é valorizado por sua consistência e lealdade. As pessoas sabem que você é alguém em quem podem confiar completamente.` },

      { section: 'impressao', key_number: 5, title: 'Impressão 5', body: `As Pessoas o (a) Veem Como Aventureiro (a) - Livre, versátil, curioso (a), energético (a), adaptável, progressivo (a), viajante, independente, comunicativo (a), às vezes instável ou irresponsável.\n\nO Número 5 na Impressão faz com que você seja visto como uma pessoa aventureira, livre e cheia de energia. As pessoas percebem sua natureza curiosa e sua sede de experiências novas. Você projeta uma imagem de liberdade e versatilidade, parecendo alguém que não gosta de ser limitado por regras ou rotinas. Dá a impressão de ser progressivo, adaptável e sempre em busca de novidades. Sua energia inquieta e seu espírito aventureiro são evidentes para todos. Pode parecer alguém que gosta de viajar, conhecer pessoas novas e explorar diferentes culturas. Às vezes pode dar a impressão de ser instável ou de não conseguir se comprometer com uma única coisa, mas na verdade possui uma capacidade natural de se adaptar a qualquer situação.` },

      { section: 'impressao', key_number: 6, title: 'Impressão 6', body: `As Pessoas o (a) Veem Como Protetor (a) - Carinhoso (a), responsável, protetor (a), conselheiro (a), harmonioso (a), familiar, prestativo (a), compreensivo (a), sacrificial, às vezes possessivo (a) ou controlador (a).\n\nO Número 6 na Impressão faz com que as pessoas o vejam como alguém carinhoso, protetor e responsável. Você projeta uma energia maternal/paternal que faz os outros se sentirem seguros e acolhidos. Dá a impressão de ser alguém que se preocupa genuinamente com o bem-estar dos outros e que está sempre disposto a ajudar. As pessoas sentem que podem recorrer a você em momentos difíceis e que você oferecerá apoio e compreensão. Sua natureza prestativa e seu desejo de criar harmonia são evidentes. Pode dar a impressão de ser alguém que se sacrifica pelos outros e que coloca as necessidades da família e dos amigos acima das suas próprias. Às vezes pode parecer possessivo ou controlador, mas isso vem do seu genuíno desejo de proteger aqueles que ama.` },

      { section: 'impressao', key_number: 7, title: 'Impressão 7', body: `As Pessoas o (a) Veem Como Misterioso (a) - Intelectual, profundo (a), analítico (a), reservado (a), sábio (a), místico (a), perfeccionista, introspectivo (a), refinado (a), às vezes distante ou crítico (a).\n\nO Número 7 na Impressão faz com que você seja visto como uma pessoa misteriosa, intelectual e profunda. As pessoas percebem sua natureza analítica e sua busca pela perfeição e conhecimento. Você projeta uma imagem de sabedoria e refinamento que atrai aqueles que buscam conversas profundas e significativas. Dá a impressão de ser alguém reservado, que não se abre facilmente, mas que possui conhecimentos valiosos. Sua aura de mistério e sua aparente conexão com questões espirituais ou filosóficas são evidentes. Pode parecer distante ou crítico para alguns, mas na verdade é valorizado por sua capacidade de análise e sua busca pela verdade. As pessoas sentem que você possui uma compreensão mais profunda da vida e respeitam sua opinião.` },

      { section: 'impressao', key_number: 8, title: 'Impressão 8', body: `As Pessoas o (a) Veem Como Poderoso (a) - Ambicioso (a), eficiente, organizado (a), autoritário (a), materialista, justo (a), determinado (a), executivo (a), influente, às vezes dominador (a) ou materialista.\n\nO Número 8 na Impressão faz com que as pessoas o vejam como alguém poderoso, ambicioso e bem-sucedido. Você projeta uma imagem de autoridade e competência que inspira respeito. Dá a impressão de ser alguém que sabe como fazer as coisas acontecerem e que tem capacidade para liderar grandes projetos. Sua energia executiva e sua habilidade para organizar e administrar são evidentes. As pessoas sentem que você é alguém que pode trazer resultados práticos e tangíveis. Pode dar a impressão de ser materialista ou focado apenas no sucesso financeiro, mas na verdade possui uma visão clara de como alcançar objetivos importantes. Sua determinação e sua capacidade de tomar decisões difíceis são respeitadas.` },

      { section: 'impressao', key_number: 9, title: 'Impressão 9', body: `As Pessoas o (a) Veem Como Humanitário (a) - Compassivo (a), sábio (a), generoso (a), idealista, universal, tolerante, inspirador (a), filantrópico (a), carismático (a), às vezes dramático (a) ou impraticável.\n\nO Número 9 na Impressão faz com que você seja visto como uma pessoa humanitária, compassiva e sábia. As pessoas percebem sua visão universal e sua preocupação genuína com o bem-estar da humanidade. Você projeta uma energia de tolerância e compreensão que atrai pessoas de diferentes origens. Dá a impressão de ser alguém generoso, que se importa com causas maiores e que está disposto a se sacrificar pelo bem comum. Sua sabedoria e sua capacidade de ver o quadro geral são evidentes. Pode parecer idealista demais ou impraticável para alguns, mas é valorizado por sua compaixão e sua visão inclusiva. As pessoas sentem que você possui uma compreensão profunda da natureza humana.` },

      { section: 'impressao', key_number: 11, title: 'Impressão 11', body: `As Pessoas o (a) Veem Como Inspirador (a) - Intuitivo (a), visionário (a), espiritual, sensível, criativo (a), idealista, carismático (a), iluminado (a), às vezes nervoso (a) ou impraticável.\n\nO Número 11 na Impressão faz com que você seja visto como uma pessoa especial, inspiradora e intuitiva. As pessoas percebem sua sensibilidade aguçada e suas capacidades psíquicas naturais. Você projeta uma energia espiritual que atrai aqueles que buscam significado mais profundo na vida. Dá a impressão de ser alguém visionário, que tem acesso a insights únicos e que pode inspirar outros a alcançar seu potencial mais elevado. Sua criatividade e idealismo são evidentes. Pode parecer nervoso ou muito sensível para alguns, mas é valorizado por sua capacidade de ver além do óbvio e sua conexão com dimensões superiores.` },

      { section: 'impressao', key_number: 22, title: 'Impressão 22', body: `As Pessoas o (a) Veem Como um (a) Grande Construtor (a) - Visionário (a), prático (a), poderoso (a), organizador (a), realizador (a), influente, responsável, transformador (a), às vezes sobrecarregado (a) ou exigente demais.\n\nO Número 22 na Impressão faz com que você seja visto como alguém capaz de realizar grandes feitos e transformar visões em realidade. As pessoas percebem sua combinação única de visão espiritual e habilidade prática. Você projeta uma energia de grande potencial e capacidade de construir algo duradouro e significativo. Dá a impressão de ser alguém que pode liderar projetos importantes que beneficiem muitas pessoas. Sua habilidade organizacional e sua visão ampla são evidentes. Pode parecer sobrecarregado ou exigente demais consigo mesmo, mas é valorizado por sua capacidade de materializar grandes ideais.` },

      // ANO PESSOAL (1-9)
      { section: 'ano_pessoal', key_number: 1, title: 'Ano Pessoal 1', body: `Ano de Novos Começos - Este é um ano de início de um novo ciclo de nove anos. É tempo de plantar sementes para o futuro, tomar iniciativas e ser pioneiro. Suas ideias originais e sua independência serão testadas. Evite ser impulsivo demais e procure agir com determinação mas também com paciência. É um ano favorável para começar novos projetos, mudar de carreira ou iniciar relacionamentos importantes.` },

      { section: 'ano_pessoal', key_number: 2, title: 'Ano Pessoal 2', body: `Ano de Cooperação e Parcerias - Este é um ano para desenvolver relacionamentos, formar parcerias e trabalhar em colaboração com outros. A paciência e a diplomacia serão suas melhores ferramentas. Evite forçar situações e permita que as coisas se desenvolvam naturalmente. É um bom ano para casamento, sociedades comerciais e para cultivar amizades importantes.` },

      { section: 'ano_pessoal', key_number: 3, title: 'Ano Pessoal 3', body: `Ano de Criatividade e Expressão - Este é um ano para expressar sua criatividade, desenvolver talentos artísticos e se comunicar com o mundo. Sua popularidade aumentará e você terá muitas oportunidades sociais. É um ano alegre e otimista, mas evite dispersar suas energias em muitas direções. Concentre-se em projetos criativos e aproveite para se divertir.` },

      { section: 'ano_pessoal', key_number: 4, title: 'Ano Pessoal 4', body: `Ano de Trabalho e Construção - Este é um ano para trabalhar duro, ser disciplinado e construir bases sólidas para o futuro. É tempo de organização, planejamento e execução meticulosa de seus projetos. Pode ser um ano mais pesado em termos de responsabilidades, mas os resultados serão duradouros. Evite ser impaciente e aceite que o progresso será gradual mas sólido.` },

      { section: 'ano_pessoal', key_number: 5, title: 'Ano Pessoal 5', body: `Ano de Liberdade e Mudanças - Este é um ano de mudanças, viagens e novas experiências. Sua necessidade de liberdade será forte e você pode sentir vontade de quebrar rotinas e explorar novos horizontes. É um ano favorável para mudanças de residência, viagens, novos estudos e experimentação. Evite ser irresponsável e procure equilibrar sua necessidade de liberdade com suas responsabilidades.` },

      { section: 'ano_pessoal', key_number: 6, title: 'Ano Pessoal 6', body: `Ano de Família e Responsabilidades - Este é um ano focado em família, lar e responsabilidades pessoais. Você pode se sentir mais protetor e cuidador com aqueles que ama. É um bom ano para casamento, ter filhos, reformar a casa ou fortalecer laços familiares. Suas qualidades nutritivas e seu senso de responsabilidade serão testados. Evite ser possessivo ou controlador.` },

      { section: 'ano_pessoal', key_number: 7, title: 'Ano Pessoal 7', body: `Ano de Introspecção e Crescimento Espiritual - Este é um ano para voltar-se para dentro, estudar, meditar e buscar crescimento espiritual. É tempo de análise profunda, pesquisa e desenvolvimento da intuição. Você pode se sentir mais reservado e preferir a solidão. É um ano favorável para estudos, espiritualidade e autoconhecimento. Evite se isolar completamente e mantenha alguns contatos sociais.` },

      { section: 'ano_pessoal', key_number: 8, title: 'Ano Pessoal 8', body: `Ano de Realizações Materiais - Este é um ano para colher os frutos do trabalho dos anos anteriores. Foco em questões materiais, carreira e reconhecimento profissional. Suas habilidades organizacionais e de liderança serão testadas. É um ano favorável para expansão de negócios, investimentos e conquistas financeiras. Evite ser dominador ou muito materialista.` },

      { section: 'ano_pessoal', key_number: 9, title: 'Ano Pessoal 9', body: `Ano de Finalização e Serviço - Este é o último ano do ciclo, tempo de finalizar projetos e se preparar para um novo ciclo. É um ano de doação, serviço humanitário e conclusões importantes. Você pode se sentir mais filosófico e interessado em causas maiores. É tempo de perdoar, liberar o passado e se preparar para novos começos. Evite se apegar ao que deve ser liberado.` },

      // MÊS PESSOAL (1-9)
      { section: 'mes_pessoal', key_number: 1, title: 'Mês Pessoal 1', body: `Mês de Novos Projetos - Este é um mês para tomar iniciativas e começar novos projetos. Sua energia estará focada em começar algo novo e você se sentirá mais independente e determinado. É um bom momento para liderar, inovar e ser pioneiro em suas áreas de interesse.` },

      { section: 'mes_pessoal', key_number: 2, title: 'Mês Pessoal 2', body: `Mês de Cooperação - Este é um mês para trabalhar em equipe, formar parcerias e focar em relacionamentos. Sua sensibilidade estará aguçada e você preferirá colaborar a liderar. É um bom momento para mediar conflitos e buscar harmonia em todas as áreas da vida.` },

      { section: 'mes_pessoal', key_number: 3, title: 'Mês Pessoal 3', body: `Mês de Criatividade - Este é um mês para expressar sua criatividade e se comunicar com o mundo. Você se sentirá mais sociável e otimista. É um bom momento para atividades artísticas, sociais e para se divertir.` },

      { section: 'mes_pessoal', key_number: 4, title: 'Mês Pessoal 4', body: `Mês de Organização - Este é um mês para organizar, planejar e trabalhar metodicamente. Você se sentirá mais disciplinado e focado em detalhes. É um bom momento para colocar projetos em ordem e trabalhar em bases sólidas.` },

      { section: 'mes_pessoal', key_number: 5, title: 'Mês Pessoal 5', body: `Mês de Mudanças - Este é um mês de movimento, mudanças e novas experiências. Você se sentirá inquieto e com necessidade de liberdade. É um bom momento para viagens, mudanças e experimentação.` },

      { section: 'mes_pessoal', key_number: 6, title: 'Mês Pessoal 6', body: `Mês de Responsabilidades - Este é um mês focado em família, lar e responsabilidades pessoais. Você se sentirá mais protetor e cuidador. É um bom momento para fortalecer laços familiares e cuidar dos que ama.` },

      { section: 'mes_pessoal', key_number: 7, title: 'Mês Pessoal 7', body: `Mês de Reflexão - Este é um mês para introspecção, estudo e crescimento espiritual. Você se sentirá mais reservado e introspectivo. É um bom momento para meditação, pesquisa e autoconhecimento.` },

      { section: 'mes_pessoal', key_number: 8, title: 'Mês Pessoal 8', body: `Mês de Realizações - Este é um mês focado em questões materiais e profissionais. Você se sentirá mais ambicioso e determinado a alcançar seus objetivos. É um bom momento para negócios e conquistas materiais.` },

      { section: 'mes_pessoal', key_number: 9, title: 'Mês Pessoal 9', body: `Mês de Finalização - Este é um mês para finalizar projetos e se preparar para novos começos. Você se sentirá mais humanitário e interessado em servir aos outros. É um bom momento para concluir ciclos e se preparar para o novo.` },

      // Continue with additional sections as needed...
      { section: 'resposta_subconsciente', key_number: 1, title: 'Resposta Subconsciente 1', body: `Você reage às emergências com liderança e iniciativa. Sua tendência é tomar o comando da situação e agir rapidamente. Pode ser impulsivo em momentos de crise.` },

      { section: 'resposta_subconsciente', key_number: 2, title: 'Resposta Subconsciente 2', body: `Você reage às emergências buscando cooperação e harmonia. Sua tendência é mediar conflitos e buscar soluções pacíficas. Pode ser indeciso em momentos de pressão.` },

      // Add more sections following the same pattern...
    ];

    console.log(`📝 Inserindo ${allTexts.length} textos numerológicos...`);

    // Insert all numerology texts
    const { error: textsError } = await supabase
      .from('numerology_texts')
      .insert(allTexts.map(text => ({
        ...text,
        version: 'v3.0',
        lang: 'pt-BR',
        category: 'main',
        content_length: text.body.length,
        is_master_number: text.key_number === 11 || text.key_number === 22,
        priority: text.key_number === 11 || text.key_number === 22 ? 10 : 5
      })));

    if (textsError) {
      console.error('❌ Erro ao inserir textos:', textsError);
      throw textsError;
    }

    // Insert Cabalistic Angels (sample data)
    const angels = [
      { name: 'Nanael', category: 'Príncipe', domain_description: 'Anjo das Ciências Espirituais e da Elevação da Alma' },
      { name: 'Vehuiah', category: 'Serafim', domain_description: 'Anjo da Vontade e dos Novos Começos' },
      { name: 'Jeliel', category: 'Serafim', domain_description: 'Anjo do Amor e da Sabedoria' },
      // Add more angels as needed...
    ];

    const { error: angelsError } = await supabase
      .from('cabalistic_angels')
      .insert(angels);

    if (angelsError) {
      console.error('❌ Erro ao inserir anjos:', angelsError);
      throw angelsError;
    }

    console.log('✅ Atualização COMPLETA finalizada com sucesso!');
    console.log(`📊 Resumo: ${allTexts.length} textos + ${angels.length} anjos inseridos`);

    return new Response(JSON.stringify({ 
      success: true, 
      message: 'Conteúdo numerológico atualizado completamente',
      stats: {
        texts_inserted: allTexts.length,
        angels_inserted: angels.length,
        version: 'v3.0'
      }
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });

  } catch (error) {
    console.error('❌ Erro na atualização:', error);
    return new Response(JSON.stringify({ 
      error: error.message,
      success: false
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    });
  }
});