-- Inserir textos dos Desafios na tabela numerology_texts
INSERT INTO numerology_texts (section, key_number, lang, title, body, version) VALUES

('desafios', 0, 'pt-BR', 'Desafio 0', 'Pode escolher entre enfrentar todos os obstáculos que existem, ou não ter desafio algum a vencer. Seu Eu Superior saberá orientá-lo (a), pois a sua alma possui a inteligência do significado de todos os números, e conhece os meios de superar todas as fraquezas. O desafio zero indica ser uma alma que conserva latentes os conhecimentos trazidos de outros ciclos da existência. Pode também ser o mais penoso de todos os desafios para quem não cultiva o amor, a compreensão, o autoconhecimento. É o desafio da escolha. É provável que tenha dificuldade em agir conforme suas preferências. O desafio zero indica que poderá ser evoluído (a) para tomar suas próprias decisões. Deve atentar para todos os desafios sem uma ênfase especial em qualquer deles. Fique atento (a) para quais armadilhas a vida lhe reserva. Para encarar o desafio zero é preciso ter controle de todos os outros desafios: a independência do 1, a diplomacia do 2, o otimismo do 3, a aplicação do 4, a compreensão do 5, o ajuste e sincronia do 6, a sabedoria do 7, o poder construtivo do 8.', '1.0'),

('desafios', 1, 'pt-BR', 'Desafio 1', 'Falta de iniciativa e dificuldade para decidir. Tendência para a solidão ou para a independência extrema. Precisa desenvolver a força de vontade, a coragem e o caráter, ou estará sujeito (a) a ser dominado (a) e mantido (a) em humildade diante dos outros, principalmente dos próprios parentes. Surgirão divergências, das quais deve se libertar, sem imputar culpa aos outros ou ressentir-se e se tornar beligerante. Pode se achar vacilante e voltar-se em todas as direções para agradar aos outros. Sofrerá a intromissão de estranhos e não agradará a ninguém nem a si próprio enquanto for fraco (a) e indeciso (a). Precisa persistir e se tornar determinado (a) a exigir respeito dos outros, respeitando-se, antes, a si mesmo (a). Precisa confiar em suas ideias criativas e originais. Deve avaliar seus planos antes de executá-los, assegurando-se de que são viáveis, plausíveis e racionais. Certo (a) e seguro (a) do que vai fazer, deve seguir em frente com firmeza e decisão.', '1.0'),

('desafios', 2, 'pt-BR', 'Desafio 2', 'Dualidade, vacilação, extrema sensibilidade; falta de autoconfiança. Precisa desenvolver a confiança em si próprio (a) ou se tornará muito inibido (a). É muito sensível e vulnerável, por isso se magoa e acha difícil perdoar. Se acalentar um complexo de inferioridade, poderá se tornar capacho dos outros. Deve se fortalecer a fim de não se sentir ofendido (a) pela menor provocação ou por fatos criados pela sua própria imaginação. É importante que cultive um ponto de vista mais amplo e pare de voltar tudo para si próprio (a), não se deixar levar pela tendência a copiar os outros e usar seus próprios talentos. Não deve sacrificar sua sinceridade só por gostar de preservar a paz, nem evitar a verdade por querer harmonia, para ser amável, ou apenas para dar boa impressão.', '1.0'),

('desafios', 3, 'pt-BR', 'Desafio 3', 'Tendência para o desperdício de energia e a falar em excesso, ou emudecer demais. Precisa aprender a não dispersar seus talentos, pois tende a fazer muitas coisas ao mesmo tempo. Aprenda a tolerar críticas, a enfrentá-las; cultive amigos e viva em sociedade, pois se temer as críticas poderá se tornar recluso (a). Precisa aprender a não ser extravagante impelido pelo desejo de ser diferente das outras pessoas. Evite falatórios e mexericos, pois sempre acabarão sendo atribuídos a si próprio (a), causando-lhe aborrecimentos. Não se deixe dominar pela melancolia ou autocomiseração, tais sentimentos são nocivos e destrutivos. Exponha seus talentos, pois assim estará proporcionando alegria a todos, melhorando o mundo e se realizando pessoalmente.', '1.0'),

('desafios', 4, 'pt-BR', 'Desafio 4', 'Tendência para a falta de organização ou para o excesso de normas; para a preguiça ou preocupação excessiva com pouca coisa. Precisa aprender a disciplinar-se com relação a ser metódico (a), pontual e sistemático (a), para encontrar facilidade no seu progresso, desenvolvendo, assim, o grande senso de valores que possui. Deve evitar ser preguiçoso (a), teimoso (a) e dogmático (a), ou negligente com os detalhes e a não se importar com os compromissos ou encontros marcados. É prudente que procure dominar essas inclinações que são poderosos obstáculos ao seu progresso. Em geral, esse desafio mostra sua tendência para não gostar do trabalho e da poupança e, com frequência, a adiar o que tem a fazer ou fazê-lo de modo negligente. Está sujeito (a) a mudanças e inquietações constantes que criam uma tendência a se preocupar desnecessariamente. Para vencer esse desafio deve inspirar segurança e solidez. Persistindo na negatividade mostra irresponsabilidade e fecha as portas à sua frente. Terá sucesso se desenvolver o lado prático de sua natureza e confiar no seu raciocínio lógico.', '1.0'),

('desafios', 5, 'pt-BR', 'Desafio 5', 'Excesso ou falta de atividade; instabilidade emocional e material. Fuga da responsabilidade, sexualidade intensa, impulsividade excessiva que pode implicar em adiamentos. Precisa aprender a conter o desejo por liberdade a qualquer preço; se não conseguir refrear esse desejo, dificilmente conseguirá construir um alicerce sólido na vida. Não deve se deixar levar por caprichos inconsequentes, provocando mudanças só para satisfazer seus desejos sensoriais, ou materiais, ou atraído por novas experiências. A busca por liberdade é um desejo natural, porém, deve refletir e analisar se o querer ser livre não é na realidade pretexto para fugir de responsabilidades. É essencial, para conquistar a liberdade realmente, aprender a se desprender de pessoas e coisas somente por motivos importantes, cultivar um tipo sadio de mudança sabendo discernir quando e o que deve ser descartado, pois assim encontrará o sucesso. A curiosidade no que se refere ao sexo e aos sentidos físicos pode torná-lo (a) inconstante e causar a infelicidade sua e de outras pessoas. Pode se tornar impulsivo (a) demais e querer tentar tudo ao mesmo tempo o que o (a) levará a perder estabilidade.', '1.0'),

('desafios', 6, 'pt-BR', 'Desafio 6', 'Excesso de responsabilidade familiar; prepotência. Seja idealista e não dominador (a). Evite influir na vida dos outros sem ser convidado (a), evitando aconselhar ou criticar fora de propósito. Não queira que todos vivam pelos seus princípios ou pela sua maneira de pensar, e não seja positivo (a) demais sobre o que considera certo ou errado. Precisa evitar discutir com qualquer um que esteja em desacordo com as regras que elaborou. Terá mais sucesso ficando ligado (a) aos seus ideais e tentar materializá-los; não se agarre às pessoas para isso. Conseguirá equilibrar a sua felicidade ao aprender que os outros têm direito às suas próprias ideias e padrões. Evite ser intransigente com colegas, sócios ou auxiliares. Evite o egoísmo, a dominação e falta de compreensão. Para vencer este desafio cultive o amor, a compreensão e o respeito pelas opiniões dos outros. Cuidado com hipocrisia e falsidades.', '1.0'),

('desafios', 7, 'pt-BR', 'Desafio 7', 'Arrogância e excesso de vaidade e falta de autoanálise. Escapismo, medo de pobreza, medo de ficar só e de rejeição, falta de fé. Mostra-se rebelde contra os tipos de pressão e tiranias e as hipocrisias morais, enfim, contra as condições e a situação prevalecente da vida em sociedade. Com isso tende a não fazer esforço algum para alterá-las ou melhorá-las, nem trabalhará para promover algo, revoltando-se consigo mesmo (a). Seu momento é um teste de repressão. Excesso ou falta de orgulho, insociabilidade e reserva, são capas para as frustrações. Esconde seus verdadeiros sentimentos sob aparente agressividade. Precisa de boa orientação educacional, a fim de desenvolver análise aguda e habilidades técnicas, audácia e perseverança. Podem surgir crises de melancolia que, se não as controlar, podem debilitar a sua saúde. Não se permita sufocar pela amargura, buscando no recurso da bebida uma rota de fuga, só porque se sente incompreendido (a) pelos o (a) cercam. Isso pode se tornar um hábito. Reduza o tempo que fica respirando suas limitações e desenvolva suas qualidades espirituais. Este é um desafio difícil e trágico de suportar, pois vê e conhece o que está errado no mundo, nas pessoas, e sabe que não pode corrigir tudo. Estude bem as suas possibilidades e faça só o que estiver ao seu alcance e puder.', '1.0'),

('desafios', 8, 'pt-BR', 'Desafio 8', 'Cuidado com desperdício, preocupação excessiva com dinheiro, sede de poder e medo da invalidez. Liberdade pessoal baseada em posses materiais é seu principal objetivo de, habitualmente, lutar por dinheiro e poder. Teme carência, perdas ou limitações e acaba atraindo-as. É um desafio de grande tensão; precisa desenvolver uma mentalidade filosófica para ver os dois lados de cada situação: querer dinheiro para seu conforto ou ser dominado por ele, querendo cada vez mais, como ideia fixa. Precisa cultivar o bom senso e o equilíbrio, tendo em vista sempre que o dinheiro existe para servir e não para escravizar. Vencendo este desafio da ambição desmedida e insensata terá oportunidade de crescimento, promoção e reconhecimento. Seus motivos para acumular fortuna devem ser razoáveis e fora de qualquer censura.', '1.0');