-- Add remaining Segundo Momento Decisivo texts (7-9, 11, 22) and Sequências Negativas
INSERT INTO numerology_texts (section, key_number, title, body, lang) VALUES 
('Segundo Momento Decisivo', 7, 'Segundo Momento Decisivo 7', 'É uma fase de introspecção, de meditação e estudo do significado mais profundo da vida, de investigação e desenvolvimento de habilidades. Caso não esteja casado (a), este pode não é o momento melhor para casamento. Isso não significa, no entanto, que não possa se casar. Velhos relacionamentos que não produzem mais frutos podem e devem ser deixados para trás. Normalmente sentirá vontade de se retirar para dentro de si para desenvolver os seus recursos internos, o que de certa forma poderá causar problemas de relacionamento, tanto a nível pessoal como familiar. Poderá surgir certo desinteresse por assuntos materiais e pouca preocupação com negócios práticos, acarretando um pouco de escassez financeira. O Segundo Momento Decisivo 7 indica possibilidades de boa evolução nos assuntos financeiros, bem como nos assuntos relacionados à ciência, porém, é um período permeado de buscas religiosas, espirituais, filosóficas ou esotéricas que poderão influenciar sua vida e tornar mais lento o seu progresso material. Os benefícios deste Momento decisivo serão muito mais profundos e interiores.', 'pt-BR'),

('Segundo Momento Decisivo', 8, 'Segundo Momento Decisivo 8', 'É um período de grandes realizações no mundo dos negócios. As despesas poderão ser altas, porém, é uma excelente fase para correr atrás dos objetivos, de conquistar poder, fama e sucesso material. Com dedicação, estudo, organização e trabalho sistemático, com objetivo definido e colaboradores aptos e interessados, dificilmente deixará de conseguir tudo o que deseja. O Segundo Momento Decisivo 8 indica um período de sua vida em que estará inclinado (a) a se tornar profundamente envolvido (a) em ser um (a) executivo (a), ou talvez estar casada (o) com um (a). A maturidade o (a) levará a confiar mais em sentimentos racionais do que emocionais. Será mais ambicioso (a) e orientado (a) para o sucesso.', 'pt-BR'),

('Segundo Momento Decisivo', 9, 'Segundo Momento Decisivo 9', 'Traz a oportunidade para cultivar o amor, a solidariedade, o altruísmo e para viagens. Poderá haver algum tipo de perda ou desapontamento, principalmente entre amigos. Um bom investimento é fazer obras humanitárias durante esse período, pois os frutos dessa plantação são certos, e o sucesso e a fama se farão presentes. A atitude nesse período da vida será mais humanista, solidária e emocional. O Segundo Momento Decisivo 9 indica um período da vida em que a pessoa expressará ideias humanitárias muito emocionais e dramáticas. Cultive a tolerância e a compaixão. Poderá desenvolver uma visão universal do mundo e trabalhar de modo a beneficiar o ser humano.', 'pt-BR'),

('Segundo Momento Decisivo', 11, 'Segundo Momento Decisivo 11', 'Por ser um número altamente espiritual e elevado, nesse período a pessoa se sente tensa e muito nervosa, principalmente durante o Primeiro Ciclo de Vida. É uma excelente fase para estudar esoterismo, espiritualismo e expandir os horizontes. Esse momento traz inspiração, iluminação e, quase sempre, fama e prestígio nacional e até internacional. Não faça nada nem diga por trás o que não teria coragem de dizer ou fazer na frente das pessoas. O Segundo Momento Decisivo 11 indica um período de trabalho inspirado e oportunidades para desenvolver o lado espiritual, aplicando nas suas atividades cotidianas as ideias inspiradas ou intuídas. Possibilidade de reconhecimento e sucesso em sua vida.', 'pt-BR'),

('Segundo Momento Decisivo', 22, 'Segundo Momento Decisivo 22', 'É, sem dúvida alguma, o Momento mais poderoso. A pessoa se sente altamente criativa, e nesse estado torna-se possível quase todas as realizações. É uma fase de interesses pelos problemas mundiais e de grande expansão da consciência. O Momento Decisivo 22 é tão poderoso que não pode acontecer no primeiro ciclo da vida. O Segundo Momento Decisivo 22 indica um período de grandes realizações em sua vida. Pode ser que se perca entre as suas ambiciosas pretensões, achando que pode tudo. É um período de trabalhar os aspectos altruístas das conquistas materiais, aplicando parte do seu tempo e recursos em ações que beneficiem a humanidade.', 'pt-BR'),

-- Add Sequências Negativas
('Sequências Negativas', 111, 'Sequência Negativa 111', 'A pessoa fica limitada, perdendo a coragem de se aventurar em algo novo. Pode, também, ficar um longo período inativo (a), desempregado (a) ou mesmo impotente para realizar o que quer que seja permanecendo nesse estado o tempo que durar o Arcano que domina o período. Esta sequência indica, eventualmente, tendência para desenvolver alguns distúrbios ou doenças cardíacas.', 'pt-BR'),

('Sequências Negativas', 222, 'Sequência Negativa 222', 'Esta sequência indica possibilidade de timidez e indecisão, podendo levar o (a) seu (a) possuidor (a) a ser subjugado (a) por aqueles mais próximos, sejam eles amigos, sócios, colegas de trabalho ou simplesmente conhecidos. Faz perder a autoestima, limitando-o (a) quanto a seus projetos e realizações. Pode, eventualmente, surgir alguma doença que provoque dependência.', 'pt-BR'),

('Sequências Negativas', 333, 'Sequência Negativa 333', 'Indica possibilidade de ser incompreendido (a), dificuldade no diálogo, principalmente com colegas de trabalho e com a (o) companheira (o). Tem dificuldade de se impor em seus projetos e para convencer as pessoas. Esta sequência pode, eventualmente, indicar possibilidade de doenças respiratórias ou de articulações.', 'pt-BR'),

('Sequências Negativas', 444, 'Sequência Negativa 444', 'Reflete dificuldade na realização profissional. Pode ser mal remunerado (a) e as perspectivas profissionais serem difíceis, ou ter dificuldade em se manter no emprego, ou se dar bem em qualquer atividade. Pode, eventualmente, indicar possibilidade de doenças reumáticas ou arteriais.', 'pt-BR'),

('Sequências Negativas', 555, 'Sequência Negativa 555', 'Indica possíveis mudanças não desejadas de casa, de profissão ou meio social. Sob esta influência, a pessoa tem frequentes altos e baixos, não se fixando profissionalmente, sempre à procura de melhores oportunidades, e ter dificuldade para as encontrar. Pode, também, causar fuga do meio social em que habita e a desenvolver alguma doença de pele.', 'pt-BR'),

('Sequências Negativas', 666, 'Sequência Negativa 666', 'Indica possibilidade de haver decepções com amigos, sócios, parentes e até com o cônjuge (namorada (o) ou companheira (o)), que não o (a) compreende em seus propósitos e sentimentos. Algum tipo de doença cardíaca pode aparecer nesse estado.', 'pt-BR'),

('Sequências Negativas', 777, 'Sequência Negativa 777', 'Faz com que se afaste de tudo e de todos. Pode levar ao desmando, transforma-lo (a) em um ser dependente, vaidoso (a), arrogante e, consequentemente, vítima da própria intolerância. A persistência nesse sentimento provoca sentimentos de solidão, doenças nervosas, dependências e, eventualmente, algum tipo de câncer.', 'pt-BR'),

('Sequências Negativas', 888, 'Sequência Negativa 888', 'Esta sequência torna arredio (a), afastando-o (a) das atividades sociais. Caso não seja evoluído (a) espiritualmente, poderá descontrolar-se emocionalmente com muita facilidade. Sob esta vibração, poderá oscilar entre a riqueza e a pobreza e, como consequência desse estresse, poderá desenvolver alguma doença.', 'pt-BR'),

('Sequências Negativas', 999, 'Sequência Negativa 999', 'Reflete uma tendência a passar por dificuldades financeiras, eventualmente perdas de bens, eventuais fracassos nos negócios e vários tipos de provações provocadas pelos períodos de estagnação. Tudo isto pode afetar o sistema nervoso e o coração.', 'pt-BR');