-- Inserir textos dos Arcanos 31-60 na tabela numerology_texts
INSERT INTO numerology_texts (section, key_number, lang, title, body, version) VALUES

('arcanos', 31, 'pt-BR', 'Arcano 31', 'O sucesso nos empreendimentos depende de vontade, firmeza e perseverança. Representa esforços compensados, vitória depois da luta; reconhecimento, conquistas e sucesso. Triunfo pela perseverança e exemplo. Risco de se tornar orgulhoso.', '1.0'),

('arcanos', 32, 'pt-BR', 'Arcano 32', 'Pressagia concurso de circunstâncias favoráveis ao êxito das empresas, se o consulente não exceder o fim a que se propõe; energias opostas criando agitação e inquietude; luta contra o dragão da realidade material para atingir os objetivos. Representa luta pela vida e poder, competição, respeito pelos outros; desafio pondo à prova as habilidades. Contendas, disputas, embates, espírito esportivo e confronto de ideias. Risco de instabilidade nos ímpetos.', '1.0'),

('arcanos', 33, 'pt-BR', 'Arcano 33', 'Significa um período de recompensa pelos esforços empreendidos; realização do sucesso esperado; empresas sérias e estáveis; associação, aliança, reunião, contrato, êxito, adiantamento; momento de desfrutar dos resultados do trabalho. Representa o fim de um trabalho bem feito e a satisfação proporcionada, ambientes e sensações agradáveis; boa comunicação, alegria, sociabilidade. Estabilidade e realização; o valor das pequenas conquistas. Risco de desprezar o valor das pequenas conquistas.', '1.0'),

('arcanos', 34, 'pt-BR', 'Arcano 34', 'Denota começo de êxito nos empreendimentos, inovações felizes, espírito de invenção; poderá receber ajuda de alguém de sua confiança; bases firmes e os negócios tendem a prosperar. Representa a união que cria a força; criatividade e associações férteis, visão de longo alcance; a ética pessoal. A virtude está em se reconhecer o que é necessário para seguir em frente.', '1.0'),

('arcanos', 35, 'pt-BR', 'Arcano 35', 'Significa o equilíbrio, ou desequilíbrio, dos ímpetos; grande capacidade e intuição; formulação de um novo projeto, de um objetivo ou de uma ideia; o futuro parece brilhante, mas guarda seus segredos e mistérios. Representa o poder que se manifesta como cooperação e ajuda; a dualidade que se manifesta como cooperação e assistência, mas que traz o componente da indecisão, da apatia; dividir para multiplicar. Risco de se tornar arrogante.', '1.0'),

('arcanos', 36, 'pt-BR', 'Arcano 36', 'Representa a força criativa propulsora das novas ideias, a inspiração, a determinação e a coragem; novos horizontes e a disposição para arriscar-se; os estágios iniciais de um novo empreendimento ou o nascimento de algo ou de uma criança. Risco de inflexibilidade.', '1.0'),

('arcanos', 37, 'pt-BR', 'Arcano 37', 'O controle emocional. É o momento de experimentar um aspecto ambivalente da própria personalidade, ou seja, o conselheiro, o ouvinte, aquele que pode curar os outros com suas palavras e carinho. Representa o plano arquetípico das emoções e sentimentos; a força dos sentimentos espirituais na alma; o fluir dos sentimentos; a sensibilidade, a honestidade e a generosidade masculinas; autoajuda. Risco de desonestidade e hipocrisia masculina.', '1.0'),

('arcanos', 38, 'pt-BR', 'Arcano 38', 'Maturidade emocional. É o momento de encontrar-se com o profundo, desconhecido e paradoxal mundo dos sentimentos que traz dentro de si; anuncia justiça, favores e proteção; o agente catalisador dos sentimentos mais profundos. Representa o plano arquetípico das emoções estéticas, o plano criativo e a inteligência ativa feminina; a espera para obter clareza. Risco de preguiça e pouca afabilidade feminina.', '1.0'),

('arcanos', 39, 'pt-BR', 'Arcano 39', 'É tempo de experimentar a incrível e mágica dimensão do amor, a conexão com as emoções; indica uma possível proposta de casamento, ou mesmo o momento de se apaixonar; uma proposta de trabalho, ou o envolvimento com ideais mais elevados. Representa as emoções e os sentimentos no plano formativo; chegada de novas amizades e afeições; reconciliação, cordialidade e paz. Risco de abuso de confiança.', '1.0'),

('arcanos', 40, 'pt-BR', 'Arcano 40', 'É indício de algo novo no plano afetivo, que pode ser um relacionamento ou uma nova perspectiva emocional dentro de um relacionamento existente, ou até mesmo o nascimento de uma criança. Representa as emoções no plano do desejo e temor; proposta amorosa e oferta afetuosa; reconciliação, consideração e promoção. Sensibilidade emocional. Risco de sedução e zombaria.', '1.0'),

('arcanos', 41, 'pt-BR', 'Arcano 41', 'É a experiência da felicidade desejada; um período de muito contentamento e de harmonia permanente nos domínios do coração; realização das suas esperanças e sonhos; vida feliz; muitas simpatias. Representa o sucesso no nível emocional e dos sentimentos; a felicidade familiar compartilhada; boa reputação e um lar feliz. A saciedade que leva á plenitude da felicidade pela autorrealização. Risco de se tornar dependente dos outros.', '1.0'),

('arcanos', 42, 'pt-BR', 'Arcano 42', 'Os seus desejos poderão agora ser realizados; um período de satisfação e alegrias, de realizações de sonhos e projetos; fortuna, honras, glória e reputação; vitória, êxito, ganho, triunfo, prosperidade, lealdade, boa-fé, franqueza, verdade. Representa a felicidade, o bem-estar e a segurança material; alegria de viver e o desfrutar do êxito. Risco de excessos e luxúria, escapismo e fuga.', '1.0'),

('arcanos', 43, 'pt-BR', 'Arcano 43', 'É a necessidade de buscar um sentido para a vida e para suas relações amorosas; necessidade de despertar e desistir de alguma coisa; excessivo interesse pelos prazeres que pode levar a escândalos amorosos; paixões violentas, divórcio, mau casamento, sedução. Representa a busca espiritual pelo abandono do material; partida difícil. A indolência e contrariedade; hora de perceber qual é o seu papel na relação. Risco de abandono cruel.', '1.0'),

('arcanos', 44, 'pt-BR', 'Arcano 44', 'É reflexão, pensamento, talentos; uma situação emocional em que existem muitas possibilidades aparentes, mas o indivíduo está diante do desafio de optar e agir em termos realistas para que aquelas potencialidades possam se manifestar. Representa megalomania e ilusões; a realidade onírica, fantasias e êxito de pouco valor.', '1.0'),

('arcanos', 45, 'pt-BR', 'Arcano 45', 'É a felicidade que vem do passado; o prazer. Possível encontro ou reencontro com pessoa de significado, ou o retorno de um amor antigo, de um sonho acalentado há muito que poderá ser realizado num futuro próximo. Ser feliz por si mesmo; entregar-se ao momento e ser feliz. Representa ânsia pelo passado, pela infância, com recordações felizes, paz interior por aceitação do passado; sonhos. Risco de apego ao passado que traz melancolia, ou de buscar o prazer nos outros.', '1.0'),

('arcanos', 46, 'pt-BR', 'Arcano 46', 'É final de uma relação ou amizade com sofrimento; remorso; algo não deu certo, uma possível traição abrindo espaço para a tristeza e o arrependimento; separação num relacionamento, mas que pode não significar um rompimento definitivo. Representa a alegria perdida, tristezas, lamentações e prazeres obscuros; despedida dolorosa, amargura, depressão, fracasso e resignação. Frustração e arrependimento.', '1.0'),

('arcanos', 47, 'pt-BR', 'Arcano 47', 'O prazer excessivo que costuma conduzir ao cansaço e ao desejo de coisas ainda maiores, talvez impossíveis de alcançar; aparente inocência, mas com um aguilhão desagradável escondido exigindo moderação nas relações e em tudo o que tenha a ver com as emoções. Representa aborrecimento e depressão, insatisfação e traições; inconstância nos sentimentos e falta de motivação, apatia, mau humor e ciúmes. Ostentação e saciedade com risco de tédio.', '1.0'),

('arcanos', 48, 'pt-BR', 'Arcano 48', 'Êxito, começo de um novo estilo de vida, de um novo relacionamento, o nascimento de uma criança ou qualquer outra situação promissora de realização emocional. Porém, cada uma dessas situações é também um princípio, uma iniciação em níveis mais profundos das experiências do coração e o indício de novas descobertas para o futuro. Representa abundância, amizades, alegria, diversão, celebrações e sucesso; gratidão. Risco de se tornar autossuficiente e dissimular os sentimentos.', '1.0'),

('arcanos', 49, 'pt-BR', 'Arcano 49', 'Abundância, equilíbrio emocional, amizades e celebração. Entendimento, amizade profunda ou amor; início de um relacionamento; também uma reconciliação, um encontro ou um acordo comercial; quase sempre sugere uma relação entre duas pessoas; poder de atração. Representa amor, afeição e amizade; união afetiva ou casamento; harmonia. Risco de dependência emocional.', '1.0'),

('arcanos', 50, 'pt-BR', 'Arcano 50', 'Início de coisas: amor, alegria ou saúde. Representa o poder dos sentimentos; amor, abundância, alegria e prazer; a escolha certa da oportunidade que gera satisfação e realização. Novas emoções envolvendo os relacionamentos em geral, renovando-os. Risco de cegueira e instabilidade emocional.', '1.0'),

('arcanos', 51, 'pt-BR', 'Arcano 51', 'Significa maturidade e sabedoria, confiança; um conselheiro confiável; momento de encontrar dentro de si o dom ambivalente da liderança e da estratégia; o arrojo intelectual e a inspiração para desenvolver novos projetos. Representa o pensamento organizado e ideias claras e objetivas; espirituosidade, perspicácia, versatilidade; autoridade masculina enérgica. Risco de intelectualismo excessivo, desumanidade e cinismo masculino.', '1.0'),

('arcanos', 52, 'pt-BR', 'Arcano 52', 'Momento de se defrontar com sua própria dimensão obstinada e sua fé inabalável nos altos propósitos e ideais. Esses ideais, altivos e nobres, irão contribuir para o aperfeiçoamento da consciência e a qualidade da própria vida. Será preciso enxergar onde os problemas estão sendo criados para si mesmo ao exigir uma perfeição exagerada para si e para os outros. Representa o plano criativo ordenado pelo pensamento racional indutivo – a razão; independência, inteligência e intelecto femininos. Risco de ressentimento e dureza intelectual feminina.', '1.0'),

('arcanos', 53, 'pt-BR', 'Arcano 53', 'É momento de se preparar para eventuais mudanças repentinas em sua vida deixando de lado os antigos padrões existentes. Tais mudanças podem acontecer com uma pessoa que aparece trazendo a inquietação, o fascínio e a tendência para o rompimento, ou a concepção de uma nova ideia, ou projeto, que surge para quebrar antigas formas de pensamento, ou ainda, alguém que se oponha aos seus planos ou pensamentos. Representa a sequência ordenada do pensamento lógico no plano formativo; imprevisibilidade, controvérsia, rigor, hostilidade e agressividade. Contundência, impetuosidade e atropelo.', '1.0'),

('arcanos', 54, 'pt-BR', 'Arcano 54', 'Momento de confrontar-se com a curiosidade infantil e a predisposição maliciosa para a fofoca e o mexerico. Possibilidade de vir a se tornar vítima da intriga dos outros ou ter propensão para se envolver em pequenas disputas. Representa o pensamento aproximado na verificação do plano material; espionagem, vigilância; a discórdia semeada e a crítica esclarecedora. Defensividade.', '1.0'),

('arcanos', 55, 'pt-BR', 'Arcano 55', 'Finalização de uma situação difícil; pode ser dolorosa, mas, pelo menos o problema será encarado de frente com honestidade, para que um futuro com muito menos conflitos possa começar. A lição já se completou, e tanto a situação econômica como a saúde tendem a melhorar. Representa a ruína total e irreversível; desolação, o ponto final insuportável. Um pedido de ajuda pode ser atendido. Hora de finalizar uma ideia, um processo, uma situação que se esgotou.', '1.0'),

('arcanos', 56, 'pt-BR', 'Arcano 56', 'Um período de muita ansiedade e dúvidas com relação ao futuro. É importante examinar e identificar de onde surge a culpa por trás dos temores, em vez de se deixar escravizar por ela. Representa crueldade, desespero, preocupações, tristeza e depressão; consciência culpada, arrependimento, abatimento, tormento, insônia e medo. Pede paciência e resignação.', '1.0'),

('arcanos', 57, 'pt-BR', 'Arcano 57', 'Uma situação de dificuldade e quase impossibilidade de agir por medo das consequências; uma decisão se faz necessária, com muita prudência. Representa força paralisada, impossibilidade de ação, indecisão; confusão mental e autossabotagem; racionalidade sem emoção; um período de crises finalizando. Auto-aprisionamento mental.', '1.0'),

('arcanos', 58, 'pt-BR', 'Arcano 58', 'Momento de agir com muita diplomacia evitando os confrontos diretos para preservar ao máximo as próprias forças; pode acarretar uma desagradável sensação de falsidade e hipocrisia, mas a vida assim o exige; seus planos poderão não dar resultados positivos ou não estão dando resultados como esperava. Representa esforço inútil; falsidade, impostura, fuga; enganar-se para conseguir algo. Futilidades e subterfúgios; jogos mentais, uso de artifícios mentais; presunção.', '1.0'),

('arcanos', 59, 'pt-BR', 'Arcano 59', 'Período onde a capacidade de compreensão da mente ajuda a diminuir a dificuldade e a liberar a ansiedade provocada anteriormente para efetuar uma passagem mais serena. Representa a procura de novos objetivos; o progresso, o sucesso merecido, as viagens; novas experiências, transformação hesitante; um terreno novo; cautela. O aprendizado da ciência mental; afastar-se do problema para vê-lo em perspectiva. Risco de vitimização.', '1.0'),

('arcanos', 60, 'pt-BR', 'Arcano 60', 'Necessidade de se encarar as próprias limitações e de reconhecer que a vida deve ser vivida dentro dos limites das próprias capacidades. Representa derrotas, traições e aflições; infâmia e perfídia; o lado negro extrapolado. A derrota, tanto a sua quanto do seu adversário. Risco de humilhar os outros tendo-os como adversários.', '1.0');