-- Add Potencialidade Profissional texts
INSERT INTO numerology_texts (section, key_number, title, body, lang) VALUES 
('Potencialidade Profissional', 1, 'Potencialidade Profissional 1', 'Qualquer tipo de negócio, qualquer forma de arte. Precisa agir como pioneiro (a). É um (a) executivo (a) dinâmico (a) e desenvolto (a) quando se empenha em levar a cabo suas ideias. Mais eficiente trabalhando sozinho (a), em seu próprio negócio, ou como profissional liberal. Possui vigorosa força interior que o (a) impulsiona para as tomadas de decisões. Explorador (a) deve sempre ser o (a) patrocinador (a) de novas ideias e novos projetos. Será bem sucedido (a) como vendedor (a), advogado (a), escritor (a), designer, arquiteto (a), publicitário (a), redator (a), inventor (a), chefe de departamento, gerente, executivo (a), diretor (a), proprietário (a) de empresas comerciais ou indústrias, ou em qualquer atividade que requeira liberdade, autonomia, pioneirismo e independência.', 'pt-BR'),

('Potencialidade Profissional', 2, 'Potencialidade Profissional 2', 'Criador (a) de uma atmosfera de harmonia no ambiente de trabalho será melhor sucedido (a) trabalhando em equipe. Excelente para trabalhos minuciosos. Possui a força do silêncio e vence pelo cansaço. Professor (a) e estudante será sempre bem sucedido (a) como pesquisador (a), secretário (a), político (a), diplomata, psicólogo (a), contador (a), estatístico (a), poeta, enfermeiro (a), músico (a), dançarino (a), coletor (a) de impostos, ou em qualquer atividade em que possa fazer parte de uma equipe, de um grupo, e estar colaborando.', 'pt-BR'),

('Potencialidade Profissional', 3, 'Potencialidade Profissional 3', 'A vibração de um (a) artista performático (a), capaz de promover qualquer coisa. Consegue vender de tudo porque tem a capacidade de vender a si mesmo (a). Sabe se beneficiar através dos contatos sociais. Será bem sucedido (a) em qualquer atividade no campo das comunicações. Possui aptidões naturais para qualquer forma de arte, ator (atriz), artista no teatro, na literatura, na música, estilista, esteticista, modelo, decorador (a), pregador (a), administrador (a), executivo, crítico (a) literário (a), jornalista, publicitário (a), escritor (a).', 'pt-BR'),

('Potencialidade Profissional', 4, 'Potencialidade Profissional 4', 'Fica feliz quando está organizando e sistematizando alguma coisa. Valoriza os ganhos recorrentes da compreensão da lei da oferta e da procura. Se expressa através dos meios materiais e tem jeito para os trabalhos manuais. Qualquer atividade cujo resultado seja um produto acabado. Será bem sucedido (a) como corretor de imóveis, ecólogo (a), eletricista, mecânico (a), construtor (a), arquiteto (a), engenheiro (a), empreiteiro (a), contador (a), economista, executivo (a), escritor (a) técnico (a), músico (a) com habilidade técnica, militar, policial, bombeiro (a), médico (a), dentista, químico (a).', 'pt-BR'),

('Potencialidade Profissional', 5, 'Potencialidade Profissional 5', 'Hábil em se relacionar com pessoas de todas as raças e credos. Sabe tirar proveito de suas experiências de vida; tentará de tudo ao menos uma vez na vida. Tem facilidade para lidar com pessoas e jeito para se relacionar com público. Extraordinariamente hábil com as palavras, obtém sucesso numa atmosfera agitada e mutável. Intelectual, cientifico (a), prefere lidar com coisas concretas. Será bem sucedido (a) como vendedor (a) viajante, artista, promotor (a) de eventos, político (a), servidor (a) público (a), líder cívico (a), detetive, investigador (a), advogado (a), jornalista, publicitário (a), ator (atriz), orador (a), agente de viagens, relações públicas, policial, aviador (a).', 'pt-BR'),

('Potencialidade Profissional', 6, 'Potencialidade Profissional 6', 'Acomoda e apazigua em todas as fases da vida; lar, trabalho, mundo! Presta serviço à comunidade sem intenção de se autopromover com o objetivo de obter vantagens pessoais. Leva em conta a moralidade. Tem solução para tudo; quer educar e melhorar a condição de vida das pessoas. Será bem sucedido (a) em todos os tipos de melhorias e educação em qualquer nível: professor (a), médico (a), psicólogo (a), advogado (a), pregador (a), enfermeiro (a), gerente de restaurante, de loja de móveis, de loja de animais de estimação, de floricultura; administrador (a) hospitalar, diretor (a) de escola, assistente social, servidor (a) público, cozinheiro (a), caseiro (a), dona (o) de casa, mordomo (a), camareiro (a), nutricionista; executivo (a) em ramo de atividade que lide com produtos domésticos; músico (a), corretor (a) de imóveis, ator (atriz), artista, decorador (a) de interiores, jardineiro (a), pecuarista; executivo (a) encarregado (a) de recursos humanos; escritor (a), consultor (a).', 'pt-BR'),

('Potencialidade Profissional', 7, 'Potencialidade Profissional 7', 'Aperfeiçoar-se e por para fora o que tem dentro de si. Tem mais domínio sobre si permanecendo só. Deve se especializar; educação é importante. Investigar minuciosamente, raciocinar e se transformar numa autorrealidade. Será bem sucedido (a) como cientista, químico (a), biólogo (a), físico (a), analista, pesquisador (a), político (a), sacerdote, líder religioso (a), fundamentalista, astrólogo (a), numerólogo (a), filósofo (a), matemático (a), advogado (a), juiz (a), reitor (a) de universidade, professor (a), detetive, cirurgião (ã), radialista, mímico (a), escritor (a), editor (a), relojoeiro (a); processamento de dados, consertos de equipamentos eletrônicos, na informática, técnico (a) em comunicações, técnico (a) em instrumentos musicais, artesanatos finos e desenhos.', 'pt-BR'),

('Potencialidade Profissional', 8, 'Potencialidade Profissional 8', 'Jeito para negócios e para comércio. Tem habilidade para se encarregar de qualquer situação. Grande capacidade de concentração; bom para formar juízo sobre o caráter das pessoas. Ilimitada capacidade empreendedora. Terá sucesso como consultor (a), nos transportes, na navegação, na bolsa de valores; corretor (a), banqueiro (a), consultor (a) de investimentos, gerente de rede de lojas, proprietário (a) de estabelecimento, presidente de empresa, executivo (a) geral e, mais especificamente de jornais, gráficas e editoras; produção industrial em grande escala; investidor (a), comprador (a), vendedor (a), político (a), filantropo (a), administrador (a), agente teatral, juiz (a).', 'pt-BR'),

('Potencialidade Profissional', 9, 'Potencialidade Profissional 9', 'Conservador (a), persuasivo (a), é bem recebido (a) em todos os tipos de plateia. Sólido senso de certo e errado e disposição para servir. Não tem a dureza necessária para ser bem sucedido (a) no mundo material. Qualidades naturais de liderança e largueza de vista. Terá sucesso como escultor (a), entalhador (a), artista, ator (atriz), autor (a) teatral, professor (a), músico (a), médico (a) especialista, líder religioso (a), reformista, diretor (a) de instituição beneficente, assistente social, advogado (a), juiz (a), policial, bombeiro (a), político (a), filantropo (a), editor (a), benfeitor (a) da humanidade; profissões que exigem lidar com pessoas.', 'pt-BR'),

('Potencialidade Profissional', 11, 'Potencialidade Profissional 11', 'Líder carismático (a) para verdades universais. Consegue transmitir inspiração aos outros. Senso de equilíbrio, criativo (a) e inventivo (a), consegue unificar os propósitos e solucionar conflitos. Será bem sucedido (a) trabalhando em comunicações, cinema, televisão, fotografia; escritor (a), poeta, ministro (a), crítico (a), inventor (a), negociante de antiguidades, líder religioso (a), diplomata, professor (a), filósofo (a), psicanalista, psicólogo (a), pesquisador (a) espiritual, médium, místico (a), ator (atriz). É o (a) verdadeiro (a) artista com boas possibilidades de atingir sucesso e fama.', 'pt-BR'),

('Potencialidade Profissional', 22, 'Potencialidade Profissional 22', 'Toda e qualquer coisa que seja para o bem de todos em grande escala. É capaz de colocar a visão e a intuição a serviço de um objetivo concreto e definido. Administrador (a) magistral com vocação para negócios. Luta pela melhoria da humanidade transformando sonhos em realidade. Prático (a), talentoso (a) e adaptável é capaz de realizar qualquer coisa e fazer com que valha a pena. Será bem sucedido (a) na política, no governo, em qualquer cargo internacional; embaixador (a), inventor (a), cientista, filantropo (a), mecenas; nas comunicações, na aeronáutica.', 'pt-BR'),

-- Add Primeiro Ciclo de Vida texts
('Primeiro Ciclo de Vida', 1, 'Primeiro Ciclo de Vida 1', 'O Número 1 (um) no primeiro Ciclo de Vida indica um período difícil. Quando criança precisa aprender a desenvolver a sua individualidade. Caso não a tenha desenvolvido, certamente na juventude e adolescência, ou mesmo até à entrada do 2º Ciclo de Vida terá dificuldades emocionais, e também para se estabilizar profissionalmente. O ideal é que a criança nesse Ciclo de Vida seja educada dentro de limites que lhe dão liberdade bem dosada, nem restrita demais nem solta demais, afim de que possa se desenvolver harmoniosamente. Caso seja adulto, maior de 18 anos, e ainda esteja no primeiro Ciclo de Vida e tenha sido reprimido (a), ou seja, não tenha tido educação condizente, precisa absorver esses ensinamentos e os colocar em prática imediatamente. Este é um palco que apresenta pessoas independentes e até autoritárias. A sua necessidade, neste período da vida é de buscar aquilo que deseja. Iniciativa e ambição presentes neste Ciclo de Vida de Vida. Figura masculina em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 2, 'Primeiro Ciclo de Vida 2', 'O Número 2 (dois) no primeiro Ciclo de Vida mostra uma criança muito mimada que, possivelmente, recebeu grande influência da mãe ou dos avós. É natural que na adolescência, em vista da forte influência familiar pense em se casar o mais cedo possível, e isso é muito comum, principalmente entre os homens. Esse é um palco que apresenta submissão, afeição e amizade. A bondade e o serviço estão presentes. Aparece certa insegurança e necessidade de se auto posicionar. Figura feminina em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 3, 'Primeiro Ciclo de Vida 3', 'O Número 3 (três) no primeiro Ciclo de Vida mostra uma infância e adolescência feliz, despreocupada e com muitos amigos. Período importante para se auto expressar em alguma atividade criativa. Possibilidade de sucesso artístico na escola. Pode não ser um período particularmente favorável aos estudos, mas com certeza muitas oportunidades surgirão para expressar ideias e emoções através das artes, da música, do teatro ou da escrita. Não é um bom período para casamento devido às facilidades para diversão. É um palco que apresenta amigos e parentes em volta. Há uma necessidade de buscar alegria. Apresenta abertura para a vida. Lado social em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 4, 'Primeiro Ciclo de Vida 4', 'O Número 4 (quatro) no primeiro Ciclo de Vida é uma indicação de restrições familiares, de disciplina e trabalho duro na escola. Certamente essa criança tem, ou teve, pais e parentes de certa maneira severos impondo seu comando e não admitindo contestações. Estudos trabalhosos; a criança precisa, ou precisou, lutar para se libertar de influências repressoras. Um ciclo bastante duro e limitado sujeito a pouca criatividade, limitando-se a obedecer. Isso pode levar a ter relacionamentos por vezes difíceis, onde, normalmente o cônjuge é que manda e dita as regras. Esse é um palco que apresenta trabalho, estrutura e busca de bases. Aparece disposição de buscar segurança e há uma necessidade sentir-se buscando o que já é concretizado pelos outros. Lado material em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 5, 'Primeiro Ciclo de Vida 5', 'O Número 5 (cinco) no primeiro Ciclo de Vida indica um período de muitas mudanças e liberdade, que às vezes é demasiada grande para que se possa lidar com ela de maneira construtiva, especialmente na fase criança e adolescente. Sem orientação adequada, nesse período, o jovem pode ter problemas causados por envolvimentos precoces com sexo, álcool e drogas. É um período não pouco favorável para o casamento, e normalmente quando isso acontece dura pouco. No lado profissional também aparece alguma dificuldade de se assentar, mudando continuamente de emprego ou atividade. A estabilidade tende a acontecer somente com a entrada no segundo Ciclo de Vida. É um palco que apresenta muitos movimentos, mudanças e transformações. Há uma necessidade de situações inovadoras. Este Ciclo de Vida apresenta dinamismo. Lado físico em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 6, 'Primeiro Ciclo de Vida 6', 'O Número 6 (seis) no primeiro Ciclo de Vida mostra uma infância cheia de deveres e responsabilidades pesadas demais para a criança suportar. Os pais devem cuidar de não sobrecarregar o filho com responsabilidades demais. No todo, um período restritivo até que quando a pressão tende a diminuir e um casamento ou aventura amorosa pode acontecer. Surge ainda dificuldade em se ajustar à sociedade, pois é incompreendido (a) nos seus planos e objetivos. Esse é um palco que apresenta a família e o círculo social em primeiro lugar. A sua necessidade é de viver em grupo e com a família. Apresenta necessidade de vivenciar a união familiar e os amigos. Responsabilidade em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 7, 'Primeiro Ciclo de Vida 7', 'O Número 7 (sete) no primeiro Ciclo de Vida mostra um período muito difícil. A criança e o jovem conserva-se retraído e pode sofrer com a falta de compreensão dos pais, professores e amigos. Tal incompreensão leva, invariavelmente, ao isolamento, retraimento e até medo de encarar a vida nessa fase. No final da adolescência, por volta dos 20/21 anos de idade, em virtude dessa retração, pode desenvolver complexos de culpa e falta de autoconfiança, dificultando o seu progresso pessoal e profissional. O palco apresenta espiritualidade, religiosidade e introspecção. Necessidade de autoconhecimento. Aparece a necessidade de ser motivado a se expressar. O interior em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 8, 'Primeiro Ciclo de Vida 8', 'O Número 8 (oito) no primeiro Ciclo de Vida mostra um período de realizações e de enriquecimento intelectual. Um período forte demais para uma criança. É extraordinário para o aprendizado acerca dos aspectos materiais da vida, de poder e justiça. É nesse período que se forjam os homens de negócios, políticos, advogados e todos aqueles que pensam mais no lado material da vida. Nesse palco se apresenta o lado material da vida, a busca de realização, a intelectualidade. Necessidade de buscar equilíbrio entre os vários aspectos da vida. O exterior em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 9, 'Primeiro Ciclo de Vida 9', 'O Número 9 (nove) é o mais difícil dentre todos os primeiros Ciclos de Vida. Quando criança surge boas oportunidades educacionais, mas também muita tensão. Na adolescência sente-se confuso (a), assustado (a), nervoso (a) e tem grandes dificuldades de concentração. Um período de muita sensibilidade e espiritualidade. Normalmente a criança, ou jovem, sente-se incompreendido pelos que o cercam. Não é recomendável casar cedo, e caso o faça, normalmente não dura muito. Profissionalmente poderá enfrentar problemas de relacionamento e por isso pode permanecer inativo por longo período até a chegada o segundo Ciclo de Vida, quando então, poderá por em prática todas as suas potencialidades. Esse é um palco que apresenta movimentos, transformações, inovações, altos e baixos, exigindo adaptação e aceitação. Necessidade de trabalhar a paciência e o amor. Apresenta abertura ao saber. A vida em si está em evidência.', 'pt-BR'),

('Primeiro Ciclo de Vida', 11, 'Primeiro Ciclo de Vida 11', 'O Número 11 (onze) no primeiro Ciclo de Vida indica um período complexo e muito difícil para uma criança suportar, devido a grande inspiração que traz e uma energia espiritual muito intensa. Por ser forte, normalmente a criança/adolescente, recebe uma proteção maior de alguém da família, mãe ou avó, pois, por ser diferenciado (a), poderá sofrer discriminações por parte de colegas ou outras pessoas. Um palco que apresenta fortes emoções. Necessidade de trabalhar o autocentramento.', 'pt-BR'),

-- Add Primeiro Momento Decisivo texts (part 1)
('Primeiro Momento Decisivo', 1, 'Primeiro Momento Decisivo 1', 'É um período difícil, em que muitas vezes será necessário enorme esforço para manter-se firme em si próprio (a), dependendo apenas de si próprio para o sucesso. Exige coragem, determinação e muita força de vontade. Inúmeros acasos e situações inesperadas o (a) forçarão a enfrentar a vida pensando e agindo por si mesmo (a). O Momento Decisivo 1 gera uma inclinação por independência; desejo de expressar a individualidade por ideias originais; de conduzir e dirigir os outros, de atingir suas realizações e ser reconhecido (a) por isso. O Primeiro Momento Decisivo 1 indica uma juventude, incluindo infância e adolescência, na maior parte do tempo, provavelmente, voltada para aprender como usar suas ideias originais, como se conduzir sem se deixar levar pelo egoísmo, pela teimosia, pela centralização em si ou dominação. Este é um período para aprender sobre liderança e pode não produzir as oportunidades que se esperava. É, principalmente, um período de aprendizagem. Um Momento Decisivo 1 no primeiro Ciclo de Vida, indica uma criança agitada, voluntariosa e por vezes complicada, que será difícil controlar e compreender.', 'pt-BR'),

('Primeiro Momento Decisivo', 2, 'Primeiro Momento Decisivo 2', 'Este é o momento que demanda cooperação e diplomacia. Traz consigo a oportunidade para cultivar o tato e a compreensão. Se for amigo (a) e companheiro (a) atencioso (a) com seus semelhantes, este será um período de amizades sinceras e de relacionamentos duradouros. Excelente fase para o casamento. Se for impaciente e desatencioso (a) poderá ser uma fase de relacionamentos difíceis, de incompreensões, brigas, discussões, em que poderá causar prejuízos às pessoas que o (a) cercam. A ênfase geral desse Momento Decisivo é para a cooperação e harmonia. Você estará propenso (a) a se tornar uma pessoa muito sensível durante este período, até mesmo se isso não faz parte do seu temperamento básico. Um período para desenvolver ações em parceria, cooperação e diplomacia. Período de trabalho e, relativamente, pouco reconhecimento. O Primeiro Momento Decisivo 2 indica uma criança sensível, que pode se ferir facilmente ou se ofender. Algumas dificuldades de expressão verbal ou emocional se fazem sentir nesse período. Influência feminina, que pode ser da mãe, avó ou alguma tia especial tornando muitas vezes a criança mimada demais. Um Momento Decisivo 2 no primeiro Ciclo de Vida, é indício de uma mãe forte e dominadora, ou pai ausente – por motivo de trabalho, morte ou separação. A criança, nesse caso, pode se tornar excessivamente sensível e ter reflexos dessa sensibilidade na juventude e adolescência, dificultando dessa maneira, as possibilidades de progresso.', 'pt-BR');