-- Update Motivação texts with complete content from Word document
UPDATE numerology_texts 
SET body = 'Deseja Independência – Liberdade, liderança e controle de tudo; viver longe de pressões, ser campeão (ã) absoluto (a), realizar-se em si mesmo (a); ficar longe da mediocridade, fazer fortuna, ser elogiado (a) e atendido (a) pelo mundo; viver longe de detalhes; impor seus padrões pessoais; muito dinamismo e autossuficiência; não ser atrapalhado (a) por ninguém, ficar só.

O Número 1 na Motivação exige que você se situe sempre de forma a ficar na frente dos outros. Tem que ser o (a) primeiro (a) em tudo o que faz. O fato de ser o (a) primeiro (a) o (a) impede, obviamente, de ter muita consideração pelos outros até que suas próprias necessidades sejam satisfeitas. A liderança adquirida em vidas passadas traz agora o desejo de continuar a se empenhar numa consciência mais elevada. Torna-se independente, também, com relação às suas crenças. O desejo por pensamentos livres e independentes continua ocupando o seu anseio mais profundo. Ambicioso (a) e criativo (a), é direto (a) e não gosta de muitos detalhes, quer liderar, dirigir, dominar; às vezes é obstinado (a). Não gosta muito de receber ordens de quem quer que seja e trabalha melhor por conta própria ou em cargo de chefia. A incompreensão e a recusa em aceitar conselhos podem trazer transtornos à sua carreira e aos seus planos profissionais. Se não tiver bom nível de consciência espiritual, poderá se tornar egoísta, excessivamente vaidoso (a) e arrogante. Geralmente é impaciente e com pouco senso diplomático. Por esse motivo poderá enfrentar dificuldades no seu meio profissional ou mesmo entre familiares, amigos e companheiros afetivos. Suas boas qualidades são: confiança em si, distinção, poder executivo, dignidade e foco nos propósitos.

Quando inseguro (a) tende a ameaçar os outros, podendo agredir, ofender, se tornar inflexível, irredutível, vingativo (a) e preconceituoso (a). Cultura, educação e refinamento pessoal são características indispensáveis que precisa adquirir para o seu triunfo pessoal, profissional e principalmente afetivo.'
WHERE section = 'motivacao' AND key_number = 1;

-- Insert Motivação 22 (Master Number) if not exists
INSERT INTO numerology_texts (section, key_number, title, body, is_master_number) 
VALUES ('motivacao', 22, 'Motivação 22', 
'Deseja Ordem no Mais Alto Grau – Individualidade, paciência, diplomacia, cooperação; expressão das próprias ideias e sentimentos; otimismo, liberdade para progredir, harmonia; espiritualidade, cultura; poder material, capacidade administrativa, amor universal; empolgar as massas; talento artístico, visão e inspiração; construir o futuro. 

O Número 22 na Motivação revela o seu desejo de continuar as realizações tangíveis de vidas anteriores. Deseja a realização material. É um (a) mestre construtor (a). Sua alma ambiciona deixar o mundo como um lugar tangivelmente melhor. Necessita manter o equilíbrio mental enquanto expressa seus ideais de modo prático. A sua maior preocupação é o bem estar e a segurança de toda a humanidade. É prático (a), habilidoso (a), honesto (a), cordial, idealista, inspirado (a) e eficiente organizador (a) com grande potencial de realização. Quer dar a sua contribuição para o gênero humano. Deseja carinho e afeto, porém, em vista de sua severidade e de ser sistemático (a) em tudo e com todos, deixa de atrair e desfrutar os afetos. Inconscientemente, se deixa levar pelos sentimentos dos outros esquecendo os seus. É otimista convicto (a) e enfrenta com coragem os obstáculos, por mais difíceis que sejam. Possui grande capacidade de realização e conhecimento intuitivo. É internacionalista; seu poder e influencia são de longo alcance, e se estende por várias áreas. Possui grande capacidade para lidar com grupos eficazmente quer como administrador, incentivador ou líder ideológico ou político. 

Quando inseguro (a) tende a exploração, ganância, a buscar riqueza sem ética; ficar rancoroso (a), imprudente, corrupto (a) e manipulador (a); complexo de inferioridade e destruição em grande escala. Cultive a determinação e a persistência, e trabalhe sempre em benefício da humanidade, sem se esquecer de si próprio (a).', true)
ON CONFLICT (section, key_number) DO UPDATE SET 
  body = EXCLUDED.body,
  is_master_number = EXCLUDED.is_master_number;

-- Update Impressão 7
UPDATE numerology_texts 
SET body = 'O Número 7 na Impressão mostra uma preferência por ficar só a estar em grupo. Essa característica pode aparecer como uma distinção notável ou apenas como uma excentricidade que impede o relacionamento social. Geralmente você deixa a impressão de que tem algo a esconder ou que reluta em compartilhar com os outros, adotando assim um ar de distanciamento que não permite que os outros o (a) conheçam melhor. Mostra qualidades do (a) especialista e do (a) perfeccionista solitário (a). Suas atitudes e comportamento revelam que vê o mundo de um ponto de vista raro. Quando é finalmente compreendido (a) pelos outros, sua contribuição empresta uma qualidade de profundidade nunca sentida antes. Um ar de mistério e segredo o (a) envolve. Aparenta ser um (a) filósofo (a), místico (a), poeta (a); um (a) pensador (a), cientista e pesquisador (a), cujos afastamentos temporários são uma ocasião para suas meditações.

Demonstra ser equilibrado (a), calado (a), distante; vive numa torre de marfim. É refinado (a), bem organizado (a), calmo (a), faz autocrítica constante; é mental e não físico. É asseado (a), bem arrumado (a) e inclinado (a) a usar roupas de cores clássicas; evita cores claras ou vivas e veste-se com bom gosto. Sexualmente é realista e não é impetuoso (a). Demora para ficar suficientemente interessado (a) a ponto de se envolver num relacionamento. Seu grande desejo de se ver cercado (a) de livros numa atmosfera de paz, beleza e tranquilidade, o (a) leva a imaginar-se sábio (a); nesse refúgio espera que todos o (a) venham consultar.

Possui natureza expressiva, única e imponente; a sua personalidade única o (a) diferencia dos demais. Personalidade exigente, sincero (a), fiel e honesto (a) com os amigos, exige o mesmo deles. Vulgaridades, delongas e atitudes passivas de críticas o (a) deixam triste e depressivo (a).'
WHERE section = 'impressao' AND key_number = 7;

-- Update Expressão 11 (Master Number)
UPDATE numerology_texts 
SET body = 'O Número 11 na Expressão revela grande intuição e visão profunda da vida. Suas vibrações são as de um (a) líder espiritual, trabalhador (a) inspirado (a) para o bem da humanidade. Sua visão é ampla e mais aguçada que a da maioria dos comuns. O seu lema deve ser "amar o próximo como a si mesmo", e deve adotá-lo como base. Combina coragem, talento e poder, com fortes sentimentos de liderança. As suas fortes intuições são valiosas para conseguir sabedoria e inspiração. Poderá ser um (a) líder em negócios públicos ou civis em sua comunidade e proporcionar melhor padrão de vida aos menos afortunados. Sua aspiração de carreira poderia expressar-se através da atuação em palcos ou telas, como pregador (a) ou professor (a) dinâmico (a).

Seu padrão de comportamento deverá ser superior ao da média. De alguma forma, deverá alcançar a fama ou o reconhecimento, e uma vez que essa vibração confere grande potencial criativo, as artes ou profissões inventivas são suas escolhas mais prováveis. Possui habilidade de destampar a fonte criativa e de imbuir seu trabalho com um toque inspiracional que afetará as almas daqueles que entrarem em contato com tudo o que criar. É realmente inspirado (a)! Talvez não seja bem sucedido (a) como negociante, sentindo-se mais à vontade em profissões agitadas, como política, marketing, administração de grandes empresas ou grandes projetos esotéricos, sociais e ideológicos.

Profundo (a) conhecedor (a) da alma humana, normalmente se destaca dos demais, pois o 11 sendo um "número mestre" consegue vislumbrar em seus amigos e inimigos defeitos e virtudes que aos outros seria impossível. Tem fé em seus ideais e dificilmente volta atrás em suas decisões. Procura sempre ser justo (a), leal, compreensivo (a) e viver em harmonia com todos. Precisa estudar assuntos relativos a esoterismo, metafísica e espiritualidade; quando negligencia esses aspectos pode tornar-se indolente, indeciso (a) e sujeito à vontade dos outros, sugado (a) e comandado (a) por seres inferiores.

Como é um ser "superior", atrai inveja e conflito das pessoas ao seu redor; faz amizades e inimizades com a mesma facilidade. A animosidade, as atitudes bruscas e a banalidade lhe trazem inibição e causam prejuízo material, moral e físico. Deixa-se dominar pelo sofrimento diante da ingratidão ou da incompreensão dos que o (a) cercam, mas encontra ressurreição, vida e esperança no mais insignificante gesto amistoso dessas pessoas. Realiza-se no trabalho em empresas que exigem genialidade, profundo sentido humano, iluminação espiritual e esforço incondicional.

Não aceita a divagação, simulação e subjugação, e não consegue se ocupar de coisas que não aprova. Como todos os seres humanos que se destacam, tem certas dificuldades de adaptação ao meio e ao convívio com seres inferiores, que não o (a) compreendem, não o (a) apoiam e ainda o (a) criticam. Acredite em seus ideais e vá em frente sem se preocupar com o que os outros pensam.',
    is_master_number = true
WHERE section = 'expressao' AND key_number = 11;