-- Limpar dados existentes e inserir novos textos numerológicos a partir do PDF extraído
DELETE FROM numerology_texts;

-- Inserir textos de Motivação
INSERT INTO numerology_texts (section, key_number, title, body, lang, version, category) VALUES
('motivacao', 1, 'Motivação 1 - Deseja Independência', 'Liberdade, liderança e controle de tudo; viver longe de pressões, ser campeão(ã) absoluto(a), realizar-se em si mesmo(a); ficar longe da mediocridade, fazer fortuna, ser elogiado(a) e atendido(a) pelo mundo; viver longe de detalhes; impor seus padrões pessoais; muito dinamismo e autossuficiência; não ser atrapalhado(a) por ninguém, ficar só.

O Número 1 na Motivação exige que você se situe sempre de forma a ficar na frente dos outros. Tem que ser o(a) primeiro(a) em tudo o que faz. O fato de ser o(a) primeiro(a) o(a) impede, obviamente, de ter muita consideração pelos outros até que suas próprias necessidades sejam satisfeitas. A liderança adquirida em vidas passadas traz agora o desejo de continuar a se empenhar numa consciência mais elevada. Torna-se independente, também, com relação às suas crenças. O desejo por pensamentos livres e independentes continua ocupando o seu anseio mais profundo. Ambicioso(a) e criativo(a), é direto(a) e não gosta de muitos detalhes, quer liderar, dirigir, dominar; às vezes é obstinado(a). Não gosta muito de receber ordens de quem quer que seja e trabalha melhor por conta própria ou em cargo de chefia. A incompreensão e a recusa em aceitar conselhos podem trazer transtornos à sua carreira e aos seus planos profissionais. Se não tiver bom nível de consciência espiritual, poderá se tornar egoísta, excessivamente vaidoso(a) e arrogante. Geralmente é impaciente e com pouco senso diplomático. Por esse motivo poderá enfrentar dificuldades no seu meio profissional ou mesmo entre familiares, amigos e companheiros afetivos. Suas boas qualidades são: confiança em si, distinção, poder executivo, dignidade e foco nos propósitos.

Quando inseguro(a) tende a ameaçar os outros, podendo agredir, ofender, se tornar inflexível, irredutível, vingativo(a) e preconceituoso(a). Cultura, educação e refinamento pessoal são características indispensáveis que precisa adquirir para o seu triunfo pessoal, profissional e principalmente afetivo.', 'pt-BR', 'v3.0', 'main'),

('motivacao', 2, 'Motivação 2 - Deseja Paz e Equilíbrio', 'Prestar serviço e devoção; criar harmonia, sentir o ritmo da vida, trabalhar com os outros, ter amigos leais e boas companhias; acumular conhecimentos e coisas; conforto sem supérfluos; ser amado(a) por todos, receber convites, sentir-se compreendido(a); vencer todas as negociações; não ser exposto(a).

O Número 2 na Motivação exige colaboração, cooperação e trabalho em grupo. Você precisa aprender a trabalhar em harmonia com outras pessoas, desenvolvendo sensibilidade e diplomacia. Sua natureza pacífica busca evitar conflitos e confrontos diretos. É motivado pela necessidade de se sentir amado e aceito pelos outros, buscando sempre a aprovação e o reconhecimento afetivo. Tem talento natural para mediar situações difíceis e criar atmosfera de paz onde há discórdia.', 'pt-BR', 'v3.0', 'main');

-- Inserir seções principais faltantes
INSERT INTO numerology_texts (section, key_number, title, body, lang, version, category) VALUES
('licao-carmica', 1, 'Lição Cármica 1', 'A Lição Cármica 1 indica que você precisa desenvolver independência, liderança e iniciativa. Em vidas passadas, você pode ter sido muito dependente dos outros ou ter deixado de assumir responsabilidades que eram suas. Agora é hora de aprender a tomar decisões por conta própria, liderar projetos e desenvolver sua individualidade única.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 2, 'Lição Cármica 2', 'A Lição Cármica 2 indica que você precisa aprender cooperação, diplomacia e trabalho em equipe. Em vidas passadas, você pode ter sido muito dominador ou independente demais. Agora é hora de desenvolver sensibilidade, paciência e a capacidade de trabalhar harmoniosamente com outros.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 3, 'Lição Cármica 3', 'A Lição Cármica 3 indica que você precisa desenvolver criatividade, comunicação e expressão pessoal. Em vidas passadas, você pode ter reprimido sua criatividade ou não ter se expressado adequadamente. Agora é hora de desenvolver seus talentos artísticos e comunicativos.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 4, 'Lição Cármica 4', 'A Lição Cármica 4 indica que você precisa aprender disciplina, organização e persistência. Em vidas passadas, você pode ter sido preguiçoso ou ter evitado responsabilidades práticas. Agora é hora de desenvolver senso prático e capacidade de construir bases sólidas.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 5, 'Lição Cármica 5', 'A Lição Cármica 5 indica que você precisa aprender sobre liberdade responsável e experiências variadas. Em vidas passadas, você pode ter sido muito rígido ou ter evitado mudanças. Agora é hora de abraçar a mudança e buscar experiências diversificadas.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 6, 'Lição Cármica 6', 'A Lição Cármica 6 indica que você precisa aprender sobre responsabilidade familiar e comunitária. Em vidas passadas, você pode ter evitado compromissos familiares ou responsabilidades domésticas. Agora é hora de desenvolver senso de cuidado e proteção aos outros.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 7, 'Lição Cármica 7', 'A Lição Cármica 7 indica que você precisa desenvolver espiritualidade e conhecimento profundo. Em vidas passadas, você pode ter sido muito materialista ou superficial. Agora é hora de buscar compreensão espiritual e desenvolver sabedoria interior.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 8, 'Lição Cármica 8', 'A Lição Cármica 8 indica que você precisa aprender sobre poder material e autoridade responsável. Em vidas passadas, você pode ter abusado do poder ou ter evitado responsabilidades materiais. Agora é hora de usar o poder de forma justa e construtiva.', 'pt-BR', 'v3.0', 'main'),
('licao-carmica', 9, 'Lição Cármica 9', 'A Lição Cármica 9 indica que você precisa desenvolver compaixão universal e serviço humanitário. Em vidas passadas, você pode ter sido egoísta ou ter negligenciado o bem-estar dos outros. Agora é hora de servir a humanidade com amor incondicional.', 'pt-BR', 'v3.0', 'main');

-- Inserir Dívidas Cármicas
INSERT INTO numerology_texts (section, key_number, title, body, lang, version, category) VALUES
('divida-carmica', 13, 'Dívida Cármica 13', 'A Dívida Cármica 13 indica que em vidas passadas você pode ter usado seu poder e energia de forma egoísta ou destrutiva. Agora você deve trabalhar com dedicação extra para superar a tendência à preguiça e ao desânimo. É necessário transformar energia negativa em positiva através do trabalho constante e da disciplina pessoal. Esta dívida exige que você aprenda a usar sua força de vontade de forma construtiva, evitando atalhos e trabalhando duro para alcançar seus objetivos. A transformação pessoal é fundamental para quitar esta dívida cármica.', 'pt-BR', 'v3.0', 'main'),
('divida-carmica', 14, 'Dívida Cármica 14', 'A Dívida Cármica 14 indica abuso da liberdade em vidas passadas. Você pode ter sido irresponsável com sua liberdade, causando sofrimento a outros através de comportamentos impulsivos ou vícios. Agora deve aprender autocontrole e usar a liberdade de forma responsável e construtiva.', 'pt-BR', 'v3.0', 'main'),
('divida-carmica', 16, 'Dívida Cármica 16', 'A Dívida Cármica 16 indica que você abusou do amor e dos relacionamentos em vidas passadas. Pode ter sido vaidoso, egoísta ou ter usado os outros emocionalmente. Agora deve aprender humildade e amor verdadeiro, desenvolvendo relacionamentos baseados no respeito mútuo e na generosidade.', 'pt-BR', 'v3.0', 'main'),
('divida-carmica', 19, 'Dívida Cármica 19', 'A Dívida Cármica 19 indica abuso de poder e autoridade em vidas passadas. Você pode ter usado sua posição para benefício próprio, negligenciando responsabilidades com outros. Agora deve aprender a usar o poder de forma justa e servir aos outros com humildade e integridade.', 'pt-BR', 'v3.0', 'main');

-- Inserir Tendências Ocultas
INSERT INTO numerology_texts (section, key_number, title, body, lang, version, category) VALUES
('tendencia-oculta', 1, 'Tendência Oculta 1', 'A Tendência Oculta 1 revela uma forte capacidade de liderança e iniciativa que pode não ser aparente externamente. Você possui um potencial natural para liderar e tomar decisões importantes, mesmo que nem sempre demonstre essa qualidade abertamente. Esta energia interna o impulsiona a buscar independência e originalidade em suas ações.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 2, 'Tendência Oculta 2', 'A Tendência Oculta 2 revela uma capacidade especial para cooperação e mediação que pode não ser imediatamente visível. Você possui um talento natural para criar harmonia e resolver conflitos, mesmo que pareça reservado externamente. Esta energia interna o torna sensível às necessidades dos outros.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 3, 'Tendência Oculta 3', 'A Tendência Oculta 3 revela talentos criativos e comunicativos que podem estar dormentes ou pouco desenvolvidos. Você possui uma capacidade natural para expressão artística e comunicação, mesmo que não tenha explorado completamente essas habilidades. Esta energia interna busca formas de se expressar criativamente.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 4, 'Tendência Oculta 4', 'A Tendência Oculta 4 revela uma capacidade organizacional e prática que pode não ser evidente superficialmente. Você possui um talento natural para estruturar, organizar e construir bases sólidas, mesmo que prefira trabalhos mais conceituais externamente. Esta energia interna busca ordem e estabilidade.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 5, 'Tendência Oculta 5', 'A Tendência Oculta 5 revela um desejo profundo por liberdade e experiências variadas que pode não ser aparente externamente. Você possui uma natureza aventureira e curiosa que busca constantemente novas experiências, mesmo que aparente estabilidade superficialmente. Esta energia interna promove mudanças e crescimento.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 6, 'Tendência Oculta 6', 'A Tendência Oculta 6 revela uma forte necessidade de cuidar e nutrir outros que pode não ser imediatamente visível. Você possui um instinto natural para proteger e apoiar aqueles que ama, mesmo que apareça independente externamente. Esta energia interna busca harmonia familiar e comunitária.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 7, 'Tendência Oculta 7', 'A Tendência Oculta 7 revela uma busca profunda por conhecimento espiritual e sabedoria que pode não ser aparente superficialmente. Você possui uma natureza introspectiva e filosófica que constantemente questiona o significado mais profundo da vida, mesmo que aparente pragmatismo externamente.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 8, 'Tendência Oculta 8', 'A Tendência Oculta 8 revela uma ambição material e desejo de conquista que pode não ser evidente externamente. Você possui um impulso natural para alcançar sucesso material e reconhecimento, mesmo que aparente desapego aos bens materiais superficialmente. Esta energia interna busca conquista e realização.', 'pt-BR', 'v3.0', 'main'),
('tendencia-oculta', 9, 'Tendência Oculta 9', 'A Tendência Oculta 9 revela uma compaixão universal e desejo de servir a humanidade que pode não ser imediatamente aparente. Você possui uma natureza altruísta e humanitária que busca constantemente maneiras de ajudar outros, mesmo que aparente egocentrismo superficialmente. Esta energia interna promove serviço universal.', 'pt-BR', 'v3.0', 'main');