-- Inserir textos dos Arcanos 11-30 na tabela numerology_texts
INSERT INTO numerology_texts (section, key_number, lang, title, body, version) VALUES

('arcanos', 11, 'pt-BR', 'Arcano 11', 'Significa força de caráter; o poder espiritual vencendo o poder material e as forças impulsivas das paixões físicas e emocionais. O amor triunfando sobre o ódio. Vitória da natureza superior sobre os desejos mundanos e carnais; uma situação onde a colisão com o leão interior é inevitável, em que a administração bem conduzida da própria raiva e de todas as emoções é altamente benéfica. A coragem, a força e a autodisciplina são necessárias para dominar a situação. Representa a energia que atua transformando a matéria; a força da mente e o domínio sobre o ambiente.', '1.0'),

('arcanos', 12, 'pt-BR', 'Arcano 12', 'Significa renúncia ou sacrifício por motivos superiores; desenvolvimento das faculdades psíquicas; domínio da tentação material; transformação da personalidade através da renúncia ou do sacrifício; necessidade do sacrifício voluntário com o propósito de atingir algo muito mais valioso. Representa a abnegação e o sacrifício voluntário por uma causa justa.', '1.0'),

('arcanos', 13, 'pt-BR', 'Arcano 13', 'Significa transformação, mudança e destruição seguidas de renovação; morte de uma parte de si, para o nascimento de novas ideias e de novas oportunidades; uma transformação inevitável, um renascimento do ser interior, desde que se consiga abrir mão da parte de nós que não somos mais. Se essa experiência será dolorosa ou não, vai depender da nossa capacidade em aceitar e reconhecer a necessidade dos fechamentos. Representa as transformações profundas que a vida exige de nós; renovação e mudanças radicais.', '1.0'),

('arcanos', 14, 'pt-BR', 'Arcano 14', 'Significa moderação, adaptação, compreensão, cooperação e trabalho em harmonia com os demais; boa administração; o que imagina ocorrerá; conseguirá combinações de êxito; paz interior; necessidade de um redirecionamento no fluxo dos sentimentos e dos relacionamentos. Representa as provas a serem superadas e o otimismo e a confiança necessários para isso; adaptação.', '1.0'),

('arcanos', 15, 'pt-BR', 'Arcano 15', 'Significa enfermidade, catástrofes, excessos, imprevistos, desastres, com encadeamento às vezes voluntário; magia negra; descontentamento, depressão; escravidão da matéria; sensação de pecado e sentimento de culpa; alheamento de compreensão; timidez e incapacidade para tomar decisões; necessidade de confrontação com tudo o que está oculto e vergonhoso na base da personalidade. Representa a ideia do mal, a limitação, o medo, a ignorância que gera sofrimento; as más influências, forças perigosas e malignas, apego às ilusões e paixões, cegueira emocional e o sexo por puro prazer físico.', '1.0'),

('arcanos', 16, 'pt-BR', 'Arcano 16', 'Significa perigo, conflito, catástrofe; destruição das estruturas obsoletas e das velhas ideias; acusações falsas; opressão; mudança brusca no modo de viver. A ambição egoísta está a ponto de criar um estalido. A Torre indica quebra ou rompimento de formas e estruturas vigentes e, da mesma forma que a Morte e o Diabo, depende muito da atitude pessoal frente às dificuldades e ao sofrimento numa separação. Representa o instante em que uma forma de ser, pensar e agir é modificada por um efeito inesperado radical; cataclismos, catástrofes e acidentes.', '1.0'),

('arcanos', 17, 'pt-BR', 'Arcano 17', 'Significa inspiração, visão, esperança, idealismo; ajuda desinteressada; dons espirituais em desenvolvimento; grande amor em evidência; esperança e fé em meio às atribulações; renascimento da alegria e do amor; influência, ascendência, criatividade, contato com alguma pessoa que trará inspiração. Representa ideia ou conceito de esperança; caminhos abertos, reinício, ação e projetos favoráveis.', '1.0'),

('arcanos', 18, 'pt-BR', 'Arcano 18', 'Significa inspiração, imaginação, intuição; desenvolvimento das faculdades psíquicas latentes; viagem astral; o mundo subconsciente dos sonhos; as trevas; um período de confusão, de flutuação e de incertezas. Representa o inconsciente misterioso e oculto; inimigos ocultos, feitiçaria, escuridão, medo, intrigas e fofocas.', '1.0'),

('arcanos', 19, 'pt-BR', 'Arcano 19', 'Significa paz, amor e felicidade; uma vida bem vivida; um trabalho bem feito; despertar e renovação; assuntos legais favoráveis; alegria e prosperidade; cumulação no plano espiritual; um período de clareza, dinamismo e confiança renovada. Representa a luz presente em cada ser humano, sua sabedoria, generosidade, confiança e caráter; saúde e bem-estar.', '1.0'),

('arcanos', 20, 'pt-BR', 'Arcano 20', 'Significa renascimento de uma nova vida; que coisas maravilhosas vão ocorrer; poderá vislumbrar o que lhe prepara o futuro; transformação; verá tudo sob uma nova luz; rompimento com o convencional; propõe um período de recompensas pelos esforços empreendidos anteriormente. Representa o julgamento ou síntese que permitem a compreensão da realidade final e o transcender da mente; aproveitar as experiências passadas, renascer para vida nova; troca de ideias, popularidade, fama.', '1.0'),

('arcanos', 21, 'pt-BR', 'Arcano 21', 'Significa liberdade para ir em qualquer direção que desejar; conclusão de um trabalho bem feito; triunfo em qualquer coisa que se empreenda; um período de realizações e de totalização; o momento do sucesso, da finalização positiva de um processo ou de uma questão; o instante de alcançarmos um objetivo, de atingirmos um ideal pelo qual lutamos durante muito tempo. Representa os poderes paranormais, a dominação sobre as leis físicas e a matéria; sucesso, viagens, plenitude.', '1.0'),

('arcanos', 22, 'pt-BR', 'Arcano 22', 'Significa decisão importante; encontrar-se diante de uma escolha que deve ser decidida com cuidado, mas também com coragem e, sobretudo, atendendo a intuição e aos impulsos interiores; anuncia o advento de um novo capítulo da vida. Existe o risco, mas existe também o desejo de saltar no desconhecido. Representa as inteligências sobre-humanas, a espontaneidade, o espiritual atuando no material, o risco.', '1.0'),

('arcanos', 23, 'pt-BR', 'Arcano 23', 'Aparece um aspecto da personalidade que vai gerar novas ideias; qualidades de liderança, bondade e honestidade. É o símbolo do poder adquirido pelo mérito e pelo trabalho, sendo emblema de proteção das pessoas bem colocadas. Representa autoconfiança, motivação, empreendedorismo, sabedoria e convicção; respeitabilidade e amizades. Risco: inflexibilidade e intolerância.', '1.0'),

('arcanos', 24, 'pt-BR', 'Arcano 24', 'É símbolo de posição elevada; demonstra a força da imaginação, da constância e da objetividade; momento de oferecer e receber aconchego e proteção. Representa a ação desejada, o plano criativo; o feminino atraente e inteligente; crescimento, atividade, firmeza e amor pela vida. Risco: vaidade e orgulho.', '1.0'),

('arcanos', 25, 'pt-BR', 'Arcano 25', 'Significa partida, mudanças, fuga, dissensão, separação, abandono, início ou final de uma situação importante; o símbolo dos altos empregos secundários, da luta para conquistar uma posição, do poder adquirido pelas lutas; momento de desenvolver as qualidades exuberantes, aventureiras e voláteis contidas em si. Representa a ação necessária no plano formativo; mudança de residência, de cidade, de situação e modo de vida; entusiasmo. Risco: tensão, euforia, exibicionismo, impaciência.', '1.0'),

('arcanos', 26, 'pt-BR', 'Arcano 26', 'Significa curiosidade, entusiasmo; que é hora de identificar os lampejos criativos dentro de si e ser audacioso. Esse momento quase sempre se manifesta na forma de uma vaga sensação de insatisfação, mas que não chega a justificar uma mudança radical. Representa ação imediata no plano material; chegada de boas notícias, oportunidade, entusiasmo e aventura, bem como possibilidade de viagens. Risco: impulsividade, inexperiência levando a maus resultados.', '1.0'),

('arcanos', 27, 'pt-BR', 'Arcano 27', 'Representa situações opressivas em seu limite; falta de perspectiva, fardo pesado, excesso de responsabilidades, sobrecarga, tensões e preocupações, desentendimentos, traições, falsidades e hipocrisias; necessidade de mudar a energia; final de uma fase.', '1.0'),

('arcanos', 28, 'pt-BR', 'Arcano 28', 'Empreendimentos científicos ou misteriosos, cujo sucesso depende de muita prudência e discrição; viagens perigosas; surpresas; atraso, suspensão, adiamento, demora, obstáculo, contrariedade. Representa o poder da informação e da cultura, força física ou psíquica; conhecimentos especiais; atitude defensiva, medo de se machucar e sofrer que leva a manter uma situação que não funciona mais; desconfiança, recusa de novidades que leva a fechar-se em si. Persistência e vigilância. Risco de virar um "mártir".', '1.0'),

('arcanos', 29, 'pt-BR', 'Arcano 29', 'Significa rapidez e fluidez dos impulsos criativos; que o sucesso da sua meta está ao seu alcance e próximo; um período de ação depois de muita espera e luta; novas ideias que trarão benefícios; campo, agricultura, bens imóveis, divertimento, alegria, paz, tranquilidade; viagens por causa de dinheiro e de grandes negócios, felicidade certa; necessidade de equilibrar o orçamento. Representa a percepção dos sentimentos das outras pessoas; o imprevisto e a rapidez de ação; notícias imprevistas.', '1.0'),

('arcanos', 30, 'pt-BR', 'Arcano 30', 'Significa bravura e muita pressão no trabalho ou em outros aspectos da vida. Representa o valor e o prazer em riscos e atividades perigosas que resultam em estímulo; atividades arriscadas; defesa do interesse mediante intransigência, ameaças e concorrência. Equilibrar a força defensiva, a fim de obter vitórias em seus pontos de vista. Risco de se fixar só na defensiva.', '1.0');