-- Add remaining Terceiro Momento Decisivo texts (7-9, 11, 22)
INSERT INTO numerology_texts (section, key_number, title, body, lang) VALUES 
('Terceiro Momento Decisivo', 7, 'Terceiro Momento Decisivo 7', 'É uma fase de introspecção, de meditação e estudo do significado mais profundo da vida, de investigação e desenvolvimento de habilidades. Caso não esteja casado (a), este pode não é o momento melhor para casamento. Isso não significa, no entanto, que não possa se casar. Velhos relacionamentos que não produzem mais frutos podem e devem ser deixados para trás. Normalmente sentirá vontade de se retirar para dentro de si para desenvolver os seus recursos internos, o que de certa forma poderá causar problemas de relacionamento, tanto a nível pessoal como familiar. Poderá surgir certo desinteresse por assuntos materiais e pouca preocupação com negócios práticos, acarretando um pouco de escassez financeira. O Terceiro Momento Decisivo 7 indica possibilidades de boa evolução nos assuntos financeiros, bem como nos assuntos relacionados à ciência, porém, é um período permeado de buscas religiosas, espirituais, filosóficas ou esotéricas que poderão influenciar sua vida e tornar mais lento o seu progresso material. Os benefícios deste Momento decisivo serão muito mais profundos e interiores.', 'pt-BR'),

('Terceiro Momento Decisivo', 8, 'Terceiro Momento Decisivo 8', 'É um período de grandes realizações no mundo dos negócios. As despesas poderão ser altas, porém, é uma excelente fase para correr atrás dos objetivos, de conquistar poder, fama e sucesso material. Com dedicação, estudo, organização e trabalho sistemático, com objetivo definido e colaboradores aptos e interessados, dificilmente deixará de conseguir tudo o que deseja. O Terceiro Momento Decisivo 8 indica um período de sua vida em que estará inclinado a se tornar profundamente envolvido (a) em ser um (a) executivo (a), ou talvez estar casada(o) com um (a). A maturidade o (a) levará a confiar mais em sentimentos racionais do que emocionais. Será mais ambicioso (a) e orientado (a) para o sucesso.', 'pt-BR'),

('Terceiro Momento Decisivo', 9, 'Terceiro Momento Decisivo 9', 'Traz a oportunidade para cultivar o amor, a solidariedade, o altruísmo e para viagens. Poderá haver algum tipo de perda ou desapontamento, principalmente entre amigos. Um bom investimento é fazer obras humanitárias durante esse período, pois os frutos dessa plantação são certos, e o sucesso e a fama se farão presentes. A atitude nesse período da vida será mais humanista, solidária e emocional. O Terceiro Momento Decisivo 9 indica um período da vida em que a pessoa expressará ideias humanitárias muito emocionais e dramáticas. Cultive a tolerância e a compaixão. Poderá desenvolver uma visão universal do mundo e trabalhar de modo a beneficiar o ser humano.', 'pt-BR'),

('Terceiro Momento Decisivo', 11, 'Terceiro Momento Decisivo 11', 'Por ser um número altamente espiritual e elevado, nesse período a pessoa se sente tensa e muito nervosa, principalmente durante o Primeiro Ciclo de Vida. É uma excelente fase para estudar esoterismo, espiritualismo e expandir os horizontes. Esse momento traz inspiração, iluminação e, quase sempre, fama e prestígio nacional e até internacional. Não faça nada nem diga por trás o que não teria coragem de dizer ou fazer na frente das pessoas. O Terceiro Momento Decisivo 11 indica um período de trabalho inspirado e oportunidades para desenvolver o lado espiritual, aplicando nas suas atividades cotidianas as ideias inspiradas ou intuídas. Possibilidade de reconhecimento e sucesso em sua vida.', 'pt-BR'),

('Terceiro Momento Decisivo', 22, 'Terceiro Momento Decisivo 22', 'É, sem dúvida alguma, o Momento mais poderoso. A pessoa se sente altamente criativa, e nesse estado torna-se possível quase todas as realizações. É uma fase de interesses pelos problemas mundiais e de grande expansão da consciência. O Momento Decisivo 22 é tão poderoso que não pode acontecer no primeiro ciclo da vida. O Terceiro Momento Decisivo 22 indica um período de grandes realizações em sua vida e com certa estabilidade. A maturidade o ajudará a centrar seu foco em objetivos mais altruístas. A sua visão de mundo estará mais aguçada e abrangente. É um período de trabalhar os aspectos altruístas das conquistas materiais, aplicando parte do seu tempo e recursos em ações que beneficiem a humanidade.', 'pt-BR');