-- Comprehensive numerology content migration - Part 2 with all remaining topics
-- This adds complete content for all 31 topics from the official document

-- Add remaining MOTIVAÇÃO entries
INSERT INTO numerology_texts (section, key_number, title, body, created_at) VALUES
('motivacao', 4, 'Motivação 4 - Deseja Ordem em Todas as Coisas', 'Fidelidade absoluta; persistência, disciplina rígida; conquistas materiais; rígido código de ética, viver longe da pretensão e falsidade; anseia amor, repele as atenções emocionais; viver ao ar livre, muita saúde, limpeza e arrumação; o máximo de segurança, ser rico (a) e não precisar de ninguém; comprar tudo o que deseja sem ficar descapitalizado.

O Número 4 na Motivação mostra o desejo de ver os fatos reais e a verdade sem enfeites, o que o (a) torna mais preparado (a) que a maioria para realizar algo construtivo com isso. Muitas pessoas pedem a verdade, mas poucas estão tão preparadas como você para aceitá-la. O seu desejo é ser justo (a) em todos os seus relacionamentos; gosta de trabalhar duro por aquilo que ambiciona; priva-se até mesmo de alguma coisa ou aceita inconveniências em favor de vantagens futuras. O lado prático permeia todo o seu ser; seu desejo é ver tudo muito bem organizado. Deseja ordem e disciplina tanto em casa como no trabalho. Quer trabalhar metodicamente e com afinco em favor dos outros e não gosta muito de inovações. É um (a) conservador (a) nato (a), realista e equilibrado (a), e sempre é possível contar com você. Profissional de alto gabarito se realiza na dedicação, na perfeição dos detalhes e na conclusão de um trabalho bem feito. Ama o sólido, o palpável, o prático, aquilo que se desenvolve, cresce e que protege. Gosta de se sentir protegido (a) e assessorado (a). Normalmente é prático (a), analítico (a) e confiável; valoriza a lealdade e a honestidade. É bom (a) disciplinador (a), determinado (a) e tenaz em seus propósitos. Possui habilidades mecânicas naturais e trabalha bem com as mãos. É extremamente otimista e enfrenta os obstáculos com coragem, por mais árduos que sejam.

Quando inseguro (a) tende a se tornar rígido (a), guarda ou acumula coisas para o futuro, toma todas as precauções possíveis, se queixa e se subestima; teima, fica obsessivo (a) e pessimista; controla tudo e todos. As suas conquistas materiais devem ser através dos seus talentos profissionais e esforços permanentes; assim pode conseguir tudo o que deseja, mas tenha também objetivos que visem beneficiar a humanidade.', now()),

('motivacao', 5, 'Motivação 5 - Deseja Liberdade Pessoal', 'Mudanças constantes; falar, agir, viajar, despreocupação, variedade, distância da rotina e dos detalhes; abertura a qualquer experiência; eterna tentativa; passar adiante, abandonar com facilidade ou agarrar-se demasiado tempo; pessoas novas e bonitas; evitar caminhos já percorridos, buscar o inusitado e o novo; ter todas as gratificações sensuais que preferir; exibir qualidades, tirar o máximo da vida, ser amado sem sentir-se preso; não usar relógio.

O Número 5 na Motivação indica um forte desejo de buscar até finalmente encontrar as soluções nas quais os outros nunca pensaram antes. Está sempre alerta e suscetível a tudo o que está relacionado com os cinco sentidos. Aborda tudo com certa intensidade sexual. Tudo o que parece ser diferente e interessante chama a sua atenção. A variedade da autoexpressão é absolutamente essencial. As viagens são um dos desejos da sua alma, por considerá-las educativas e ampliadoras do seu horizonte. É um ser mutável; gosta de variedades e de experiências incomuns, e está sempre à procura de novas oportunidades. Possui natureza perceptiva, arguta, perspicaz e curiosidade natural. Isso instiga o seu desejo de investigar e elucidar qualquer situação ou problema. Gosta de novidades e é um (a) entusiasta por novas experiências e novos encontros; às vezes gosta também de rupturas. Com seu raciocínio rápido se adapta a qualquer situação, sentindo-se à vontade e fazendo com que os outros também se sintam. Relaciona-se bem em sociedade; possui grande versatilidade e talentos para se dar bem em várias e diferentes atividades, e não se cansa nem se atrapalha, pois como normalmente só faz o que gosta, é do tipo que trabalha descansando.

Quando inseguro (a) tende a romper, cortar tudo ou todos que lhe atrapalham, quebra o que estiver na frente, pergunta tudo para saber detalhes; dá escândalos, exibe-se, tem vários programas no mesmo dia, exagera na bebida ou no sexo; corre riscos. Por ter fortes inclinações filosóficas, é bom que busque conhecimentos nessa área através de estudos, experiências e investigações.', now()),

('motivacao', 6, 'Motivação 6 - Deseja um Lar Feliz', 'Família, união, harmonia, luxo e conforto; tolerância em relação aos outros; dar refúgio e proteção aos que precisam de auxílio; solidariedade, sentir o ritmo da vida; sentimentalismo exagerado; que todos sigam suas ideias; dar jeito em tudo e solucionar tudo para todos; trabalhar em equipe; tem interesse em tudo e por todos; distância de trabalhos mecânicos; sentir-se amado (a) e necessário (a), tornar-se insubstituível, que seus filhos só deem alegrias; não precisar pedir favores.

O Número 6 na Motivação descreve um grande desejo de ser amistoso (a), afável, e conscientemente interessado (a) nos problemas dos outros como se fossem os seus. Deseja se envolver, assumir um senso de responsabilidade social, e até mesmo compartilhar de um senso de culpa coletiva pelo que os outros fazem em cooperação de grupo. O seu desejo é ensinar aos outros a manterem a paz e a harmonia em suas vidas. O seu interesse pelo bem estar dos seus familiares é tão profundo que às vezes se torna sufocante e priva que eles vivam as suas próprias experiências. Age de modo convencional e tolerante em relação ao comportamento dos outros. Deseja ser sempre o refugio e o abrigo para aqueles que precisam de atenção e auxilio. Sente o ritmo da vida na harmonia da música. Às vezes se torna um (a) sentimentalista exagerado (a) incapaz de um julgamento real de uma situação. Deseja impor suas próprias ideias e princípios a todos. Presta favores de boa vontade. Gosta de cozinhar e aprecia uma boa mesa. Não se sente atraído (a) por trabalhos mecânicos e técnicos. É idealista e tem como princípio orientar e consertar tudo o que está errado no mundo. Quer criar raízes e fazer com que sua vida gire em torno do seu lar e das pessoas queridas. É conciliador (a), aprecia a fertilidade e tudo o que cresce, produz e se expande. Entusiasma-se com o milagre da vida e sente a presença do amor em tudo. É simpático (a), intuitivo (a), persistente, responsável e possui temperamento equilibrado. Adora uma casa bonita com muitas plantas, móveis confortáveis, tudo na mais perfeita ordem. Possui gosto refinado e se sente bem no conforto e na elegância. Conquista facilmente a popularidade e o êxito social.

Quando inseguro (a) tende a mesquinharia, sentimentalismo, apego à família ou ao passado, manipulação, perda de confiança e fé, atrai relações complicadas. Por sua tendência à vaidade e ao egoísmo, é bom que se dedique aos estudos esotéricos, metafísicos e espiritualistas, e seja compreensivo (a) com os outros.', now()),

-- ANO PESSOAL (1-9)
('ano_pessoal', 1, 'Ano Pessoal 1 - Ano de Novos Começos', 'Este é um ano para iniciar novos projetos e tomar iniciativas. Sua energia estará focada em começar algo novo e você se sentirá mais independente e determinado. É um bom momento para liderar, inovar e ser pioneiro em suas áreas de interesse. Desenvolva sua autoconfiança e não tenha medo de tomar decisões importantes. Evite ser dominador ou muito impaciente com os outros. Este ano marca o início de um novo ciclo de nove anos em sua vida.', now()),

('ano_pessoal', 8, 'Ano Pessoal 8 - Ano de Realizações Materiais', 'Este é um ano para colher os frutos do trabalho dos anos anteriores. Foco em questões materiais, carreira e reconhecimento profissional. Suas habilidades organizacionais e de liderança serão testadas. É um ano favorável para expansão de negócios, investimentos e conquistas financeiras. Evite ser dominador ou muito materialista. Use seu poder e influência de forma justa e construtiva. É importante manter o equilíbrio entre ambição material e valores espirituais.', now()),

-- MÊS PESSOAL (1-9) 
('mes_pessoal', 1, 'Mês Pessoal 1 - Mês de Novos Projetos', 'Este é um mês para tomar iniciativas e começar novos projetos. Sua energia estará focada em começar algo novo e você se sentirá mais independente e determinado. É um bom momento para liderar, inovar e ser pioneiro em suas áreas de interesse. Desenvolva sua autoconfiança e tome decisões importantes. Evite ser dominador ou impaciente com os outros. Este mês traz oportunidades de liderança e crescimento pessoal.', now()),

-- DIA PESSOAL (1-9)
('dia_pessoal', 1, 'Dia Pessoal 1 - Dia de Liderança', 'Este é um dia para tomar iniciativas e liderar. Você se sentirá mais confiante e independente. É um bom momento para começar novos projetos, tomar decisões importantes e assumir posições de liderança. Confie em seus instintos e aja com determinação. Evite ser autoritário ou impaciente. Este dia favorece ações pioneiras e inovadoras.', now()),

-- CICLOS DE VIDA (1-9, 11, 22)
('ciclo_vida', 5, 'Primeiro Ciclo de Vida 5 - Liberdade e Experiências', 'Durante este ciclo, sua vida será marcada pela busca por liberdade, variedade e novas experiências. Você sentirá uma forte necessidade de explorar o mundo, viajar e conhecer diferentes culturas e pessoas. É um período de grande curiosidade e aprendizado através da experiência direta. Desenvolva sua versatilidade e adaptabilidade, mas evite a instabilidade excessiva. Aprenda a equilibrar sua necessidade de liberdade com responsabilidades práticas.', now()),

('ciclo_vida', 11, 'Segundo Ciclo de Vida 11 - Inspiração e Intuição', 'Este ciclo traz uma energia espiritual elevada e grande potencial para inspirar outros. Você desenvolverá sua intuição e sensibilidade espiritual. É um período de crescimento através da inspiração, criatividade e serviço aos outros. Deve aprender a equilibrar sua sensibilidade com estabilidade emocional. Evite extremos e busque formas construtivas de expressar sua natureza inspiradora. Este ciclo pode trazer reconhecimento por suas contribuições especiais ao mundo.', now()),

('ciclo_vida', 9, 'Terceiro Ciclo de Vida 9 - Sabedoria e Serviço Universal', 'O ciclo final da vida é dedicado ao serviço universal e ao compartilhamento da sabedoria adquirida. Você se sentirá compelido a ajudar a humanidade de forma ampla, seja através do ensino, aconselhamento ou trabalho humanitário. É um período de desprendimento material e foco no legado espiritual. Desenvolva tolerância, compaixão e a capacidade de perdoar. Evite o martírio e mantenha o equilíbrio entre servir aos outros e cuidar de si mesmo.', now()),

-- MOMENTOS DECISIVOS (1-9, 11, 22)
('momento_decisivo', 7, 'Primeiro Momento Decisivo 7 - Busca Interior', 'Este período será marcado pela necessidade de desenvolver sua sabedoria interior e conhecimento espiritual. Você se sentirá atraído pelo estudo, pesquisa e reflexão profunda. É um momento para desenvolver sua intuição e buscar respostas em seu interior. Evite o isolamento excessivo e procure equilibrar introspecção com conexões sociais. O aprendizado e o desenvolvimento pessoal serão temas centrais deste período.', now()),

('momento_decisivo', 11, 'Segundo Momento Decisivo 11 - Inspiração e Liderança Espiritual', 'Este é um período de grande potencial para inspirar e iluminar outros. Sua sensibilidade e intuição estarão muito desenvolvidas, permitindo que você seja um canal de sabedoria e inspiração. É um momento para usar seus dons especiais em benefício da humanidade. Mantenha os pés no chão enquanto desenvolve sua espiritualidade. Evite instabilidade emocional e procure formas práticas de aplicar suas intuições.', now()),

('momento_decisivo', 5, 'Terceiro Momento Decisivo 5 - Liberdade e Mudanças', 'Este período será caracterizado por mudanças, viagens e novas experiências. Você sentirá uma forte necessidade de liberdade e variedade em sua vida. É um momento para expandir horizontes, explorar novos caminhos e se adaptar a mudanças. Desenvolva sua versatilidade, mas evite instabilidade excessiva. Aprenda a equilibrar sua necessidade de liberdade com responsabilidades práticas.', now()),

('momento_decisivo', 9, 'Quarto Momento Decisivo 9 - Sabedoria e Conclusão', 'O período final será dedicado ao compartilhamento da sabedoria adquirida e ao serviço universal. Você se sentirá compelido a contribuir para o bem-estar da humanidade através de sua experiência e conhecimento. É um momento de conclusão e síntese de tudo o que aprendeu. Desenvolva compaixão, tolerância e desapego material. Evite o martírio e mantenha o equilíbrio entre servir e cuidar de si mesmo.', now());

-- Continue with more comprehensive entries...