-- Inserir textos numerológicos completos para todos os números de 1 a 9 e números mestres 11 e 22

-- Limpar dados existentes e repovoar
DELETE FROM numerology_texts;

-- MOTIVAÇÃO
INSERT INTO numerology_texts (section, key_number, lang, title, body) VALUES
('motivacao', 1, 'pt-BR', 'Motivação 1 - Liderança', 'Sua motivação interna é liderar e ser independente. Você busca constantemente pioneirismo, originalidade e a chance de ser o primeiro em tudo que faz. Sua alma anseia por autonomia e pela capacidade de iniciar novos projetos.'),
('motivacao', 2, 'pt-BR', 'Motivação 2 - Cooperação', 'Você é motivado pela harmonia, parceria e cooperação. Sua alma busca trabalhar em equipe, mediar conflitos e criar ambientes de paz e colaboração. A diplomacia e a sensibilidade são suas forças motrizes.'),
('motivacao', 3, 'pt-BR', 'Motivação 3 - Criatividade', 'Sua motivação vem da necessidade de se expressar criativamente. Você busca arte, comunicação e alegria em tudo que faz. Sua alma anseia por diversão, socialização e a capacidade de inspirar outros através da sua criatividade.'),
('motivacao', 4, 'pt-BR', 'Motivação 4 - Estabilidade', 'Você é motivado pela necessidade de ordem, estabilidade e segurança. Sua alma busca construir bases sólidas, trabalhar com disciplina e criar estruturas duradouras. O trabalho árduo e a perseverança são suas características principais.'),
('motivacao', 5, 'pt-BR', 'Motivação 5 - Liberdade', 'Sua motivação interna é a liberdade e a aventura. Você busca constantemente novas experiências, mudanças e a capacidade de explorar o mundo. Sua alma anseia por variedade, movimento e independência pessoal.'),
('motivacao', 6, 'pt-BR', 'Motivação 6 - Responsabilidade', 'Você é motivado pelo desejo de cuidar, nutrir e assumir responsabilidades. Sua alma busca harmonia familiar, justiça e a capacidade de servir aos outros. O amor e a compaixão guiam suas ações.'),
('motivacao', 7, 'pt-BR', 'Motivação 7 - Espiritualidade', 'Sua motivação vem da busca por conhecimento, sabedoria e compreensão espiritual. Você anseia por introspecção, análise profunda e conexão com verdades universais. A pesquisa e o mistério o fascinam.'),
('motivacao', 8, 'pt-BR', 'Motivação 8 - Conquista Material', 'Você é motivado pela ambição, sucesso material e reconhecimento. Sua alma busca poder, status e a capacidade de realizar grandes conquistas no mundo material. A organização e a eficiência são suas ferramentas.'),
('motivacao', 9, 'pt-BR', 'Motivação 9 - Altruísmo', 'Sua motivação interna é servir a humanidade e fazer a diferença no mundo. Você busca completude, sabedoria universal e a capacidade de inspirar transformações positivas. O altruísmo e a compaixão definem você.'),
('motivacao', 11, 'pt-BR', 'Motivação 11 - Inspiração', 'Sua motivação é ser um canal de inspiração e iluminação. Você possui uma conexão especial com dimensões superiores e busca elevar a consciência das pessoas ao seu redor através da sua intuição e sensibilidade extremas.'),
('motivacao', 22, 'pt-BR', 'Motivação 22 - Construção Visionária', 'Você é motivado por visões grandiosas e pela capacidade de torná-las realidade. Sua alma busca construir legados duradouros que beneficiem a humanidade, combinando praticidade com idealismo visionário.');

-- EXPRESSÃO
INSERT INTO numerology_texts (section, key_number, lang, title, body) VALUES
('expressao', 1, 'pt-BR', 'Expressão 1 - O Líder', 'Você se expressa no mundo como um líder natural, pioneiro e inovador. Sua personalidade é marcada pela independência, determinação e iniciativa. Você tem a capacidade de abrir novos caminhos e inspirar outros a seguirem sua liderança.'),
('expressao', 2, 'pt-BR', 'Expressão 2 - O Cooperador', 'Você se expressa através da diplomacia, cooperação e sensibilidade. Sua personalidade é marcada pela gentileza, tato e capacidade de trabalhar em equipe. Você é um mediador natural e um construtor de pontes entre pessoas.'),
('expressao', 3, 'pt-BR', 'Expressão 3 - O Comunicador', 'Você se expressa através da criatividade, comunicação e alegria. Sua personalidade é marcada pela espontaneidade, otimismo e talento artístico. Você tem o dom de alegrar ambientes e inspirar outros através da sua expressividade.'),
('expressao', 4, 'pt-BR', 'Expressão 4 - O Construtor', 'Você se expressa através da praticidade, organização e perseverança. Sua personalidade é marcada pela confiabilidade, método e dedicação ao trabalho. Você é um construtor de bases sólidas e sistemas eficientes.'),
('expressao', 5, 'pt-BR', 'Expressão 5 - O Aventureiro', 'Você se expressa através da versatilidade, curiosidade e liberdade. Sua personalidade é marcada pela adaptabilidade, entusiasmo por mudanças e sede de experiências. Você é um explorador natural da vida.'),
('expressao', 6, 'pt-BR', 'Expressão 6 - O Cuidador', 'Você se expressa através do cuidado, responsabilidade e harmonia. Sua personalidade é marcada pela compaixão, senso de justiça e devotion à família. Você é um protetor natural e conselheiro confiável.'),
('expressao', 7, 'pt-BR', 'Expressão 7 - O Pesquisador', 'Você se expressa através da análise, introspecção e busca espiritual. Sua personalidade é marcada pela profundidade, intuição e necessidade de compreender os mistérios da vida. Você é um sábio em desenvolvimento.'),
('expressao', 8, 'pt-BR', 'Expressão 8 - O Executivo', 'Você se expressa através da ambição, organização e busca pelo sucesso material. Sua personalidade é marcada pela eficiência, autoridade natural e capacidade de realizar grandes empreendimentos. Você é um construtor de impérios.'),
('expressao', 9, 'pt-BR', 'Expressão 9 - O Humanitário', 'Você se expressa através da compaixão, sabedoria e serviço à humanidade. Sua personalidade é marcada pela generosidade, visão universal e capacidade de inspirar transformações. Você é um servidor da luz.'),
('expressao', 11, 'pt-BR', 'Expressão 11 - O Inspirador', 'Você se expressa como um canal de inspiração e elevação espiritual. Sua personalidade é marcada pela intuição refinada, sensibilidade extrema e capacidade de iluminar caminhos para outros. Você é um farol de luz espiritual.'),
('expressao', 22, 'pt-BR', 'Expressão 22 - O Mestre Construtor', 'Você se expressa através de visões grandiosas e capacidade de materializá-las. Sua personalidade combina idealismo com praticidade, permitindo construir projetos que beneficiam a humanidade em larga escala. Você é um arquiteto de sonhos.');

-- IMPRESSÃO
INSERT INTO numerology_texts (section, key_number, lang, title, body) VALUES
('impressao', 1, 'pt-BR', 'Impressão 1 - Autoridade', 'As pessoas o veem como alguém confiante, independente e com autoridade natural. Sua primeira impressão transmite liderança, determinação e capacidade de tomar decisões. Outros o percebem como um pioneiro e inovador.'),
('impressao', 2, 'pt-BR', 'Impressão 2 - Gentileza', 'As pessoas o veem como alguém gentil, cooperativo e diplomático. Sua primeira impressão transmite paz, harmonia e capacidade de mediar conflitos. Outros o percebem como um parceiro ideal e conselheiro sensível.'),
('impressao', 3, 'pt-BR', 'Impressão 3 - Criatividade', 'As pessoas o veem como alguém criativo, comunicativo e alegre. Sua primeira impressão transmite entusiasmo, talento artístico e capacidade de entreter. Outros o percebem como inspirador e divertido.'),
('impressao', 4, 'pt-BR', 'Impressão 4 - Confiabilidade', 'As pessoas o veem como alguém confiável, organizado e trabalhador. Sua primeira impressão transmite estabilidade, método e dedicação. Outros o percebem como alguém em quem podem confiar e contar.'),
('impressao', 5, 'pt-BR', 'Impressão 5 - Dinamismo', 'As pessoas o veem como alguém dinâmico, versátil e aventureiro. Sua primeira impressão transmite energia, curiosidade e amor pela liberdade. Outros o percebem como estimulante e imprevisível.'),
('impressao', 6, 'pt-BR', 'Impressão 6 - Carinho', 'As pessoas o veem como alguém carinhoso, responsável e protetor. Sua primeira impressão transmite calor humano, compaixão e capacidade de cuidar. Outros o percebem como um refúgio seguro.'),
('impressao', 7, 'pt-BR', 'Impressão 7 - Mistério', 'As pessoas o veem como alguém misterioso, intelectual e espiritualizado. Sua primeira impressão transmite profundidade, sabedoria e um toque de mistério. Outros o percebem como intrigante e sábio.'),
('impressao', 8, 'pt-BR', 'Impressão 8 - Sucesso', 'As pessoas o veem como alguém bem-sucedido, ambicioso e poderoso. Sua primeira impressão transmite autoridade, prosperidade e capacidade executiva. Outros o percebem como um vencedor nato.'),
('impressao', 9, 'pt-BR', 'Impressão 9 - Sabedoria', 'As pessoas o veem como alguém sábio, generoso e humanitário. Sua primeira impressão transmite compaixão, compreensão universal e maturidade. Outros o percebem como um mentor e guia espiritual.'),
('impressao', 11, 'pt-BR', 'Impressão 11 - Inspiração', 'As pessoas o veem como alguém especial, inspirador e espiritualmente elevado. Sua primeira impressão transmite sensibilidade refinada, intuição poderosa e conexão com dimensões superiores. Outros o percebem como um ser iluminado.'),
('impressao', 22, 'pt-BR', 'Impressão 22 - Visão', 'As pessoas o veem como alguém visionário, capaz de grandes realizações e transformações. Sua primeira impressão transmite poder para materializar sonhos impossíveis e liderar mudanças significativas no mundo.');

-- DESTINO
INSERT INTO numerology_texts (section, key_number, lang, title, body) VALUES
('destino', 1, 'pt-BR', 'Destino 1 - Liderança', 'Seu destino é liderar, pioneirar e abrir novos caminhos. Você veio para desenvolver independência, originalidade e capacidade de iniciativa. Sua missão é ser o primeiro, o original, aquele que mostra o caminho para outros seguirem.'),
('destino', 2, 'pt-BR', 'Destino 2 - Cooperação', 'Seu destino é cooperar, mediar e criar harmonia. Você veio para desenvolver diplomacia, sensibilidade e capacidade de trabalhar em equipe. Sua missão é ser a ponte que une pessoas e interesses diferentes.'),
('destino', 3, 'pt-BR', 'Destino 3 - Expressão', 'Seu destino é criar, comunicar e alegrar o mundo. Você veio para desenvolver criatividade, expressão artística e capacidade de inspirar. Sua missão é trazer beleza, alegria e inspiração para a vida das pessoas.'),
('destino', 4, 'pt-BR', 'Destino 4 - Construção', 'Seu destino é construir, organizar e criar bases sólidas. Você veio para desenvolver praticidade, perseverança e capacidade de trabalho árduo. Sua missão é estabelecer estruturas duradouras para o benefício de todos.'),
('destino', 5, 'pt-BR', 'Destino 5 - Liberdade', 'Seu destino é explorar, experimentar e promover mudanças progressivas. Você veio para desenvolver versatilidade, adaptabilidade e amor pela liberdade. Sua missão é quebrar barreiras e expandir horizontes.'),
('destino', 6, 'pt-BR', 'Destino 6 - Serviço', 'Seu destino é servir, cuidar e assumir responsabilidades. Você veio para desenvolver compaixão, senso de justiça e capacidade de nutrir. Sua missão é criar harmonia e bem-estar para família e comunidade.'),
('destino', 7, 'pt-BR', 'Destino 7 - Sabedoria', 'Seu destino é buscar, analisar e compreender verdades profundas. Você veio para desenvolver espiritualidade, intuição e conhecimento. Sua missão é desvendar mistérios e compartilhar sabedoria.'),
('destino', 8, 'pt-BR', 'Destino 8 - Conquista', 'Seu destino é conquistar, organizar e alcançar o sucesso material. Você veio para desenvolver ambição, eficiência e capacidade executiva. Sua missão é construir empreendimentos prósperos e duradouros.'),
('destino', 9, 'pt-BR', 'Destino 9 - Humanitarismo', 'Seu destino é servir a humanidade e promover transformações universais. Você veio para desenvolver compaixão universal, sabedoria e capacidade de inspirar. Sua missão é elevar a consciência coletiva.'),
('destino', 11, 'pt-BR', 'Destino 11 - Iluminação', 'Seu destino é iluminar, inspirar e elevar a consciência das pessoas. Você veio para desenvolver intuição superior, sensibilidade refinada e conexão espiritual. Sua missão é ser um farol de luz espiritual.'),
('destino', 22, 'pt-BR', 'Destino 22 - Construção Visionária', 'Seu destino é materializar visões grandiosas que transformem o mundo. Você veio para desenvolver a capacidade de sonhar grande e tornar esses sonhos realidade. Sua missão é construir um legado duradouro para a humanidade.');

-- ANO PESSOAL
INSERT INTO numerology_texts (section, key_number, lang, title, body) VALUES
('ano_pessoal', 1, 'pt-BR', 'Ano Pessoal 1 - Novos Começos', 'Este é um ano de novos começos, iniciativas e pioneirismo. É tempo de plantar sementes, começar projetos e tomar iniciativas. Sua energia estará focada em liderança, independência e originalidade. Aproveite para dar os primeiros passos em direção aos seus sonhos.'),
('ano_pessoal', 2, 'pt-BR', 'Ano Pessoal 2 - Cooperação e Paciência', 'Este é um ano de cooperação, parcerias e desenvolvimento de relacionamentos. É tempo de trabalhar em equipe, exercitar a diplomacia e ter paciência. Sua energia estará focada em colaboração, sensibilidade e construção de vínculos sólidos.'),
('ano_pessoal', 3, 'pt-BR', 'Ano Pessoal 3 - Criatividade e Expansão', 'Este é um ano de criatividade, comunicação e expressão pessoal. É tempo de desenvolver talentos artísticos, se comunicar mais e se divertir. Sua energia estará focada em criatividade, otimismo e expansão social.'),
('ano_pessoal', 4, 'pt-BR', 'Ano Pessoal 4 - Trabalho e Organização', 'Este é um ano de trabalho árduo, organização e construção de bases sólidas. É tempo de ser prático, persistente e focado em metas de longo prazo. Sua energia estará direcionada para estabilidade, método e realização através do esforço.'),
('ano_pessoal', 5, 'pt-BR', 'Ano Pessoal 5 - Mudanças e Liberdade', 'Este é um ano de mudanças, aventuras e busca por liberdade. É tempo de explorar novas possibilidades, viajar e experimentar coisas diferentes. Sua energia estará focada em versatilidade, movimento e quebra de rotinas.'),
('ano_pessoal', 6, 'pt-BR', 'Ano Pessoal 6 - Responsabilidade e Família', 'Este é um ano de responsabilidades familiares, cuidado com outros e busca por harmonia. É tempo de focar na família, assumir compromissos e criar ambientes harmoniosos. Sua energia estará direcionada para serviço, compaixão e estabilidade doméstica.'),
('ano_pessoal', 7, 'pt-BR', 'Ano Pessoal 7 - Introspecção e Espiritualidade', 'Este é um ano de introspecção, estudos e desenvolvimento espiritual. É tempo de se voltar para dentro, buscar conhecimento e compreender verdades profundas. Sua energia estará focada em análise, meditação e crescimento interior.'),
('ano_pessoal', 8, 'pt-BR', 'Ano Pessoal 8 - Conquistas e Sucesso Material', 'Este é um ano de conquistas materiais, reconhecimento e sucesso nos negócios. É tempo de colher os frutos do trabalho passado e buscar expansão material. Sua energia estará focada em ambição, organização e realização material.'),
('ano_pessoal', 9, 'pt-BR', 'Ano Pessoal 9 - Conclusão e Transformação', 'Este é um ano de conclusões, transformações e preparação para um novo ciclo. É tempo de finalizar projetos, se libertar do que não serve mais e se preparar para recomeçar. Sua energia estará focada em sabedoria, compaixão e renovação.');