-- Inserção massiva de textos de numerologia do Material Complementar (9)

-- MOTIVAÇÃO (números 1-22)
INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('motivacao', 1, 'Motivação 1', 'Deseja Independência – Liberdade, liderança e controle de tudo; viver longe de pressões, ser campeão (ã) absoluto (a), realizar-se em si mesmo (a); ficar longe da mediocridade, fazer fortuna, ser elogiado (a) e atendido (a) pelo mundo; viver longe de detalhes; impor seus padrões pessoais; muito dinamismo e autossuficiência; não ser atrapalhado (a) por ninguém, ficar só.

O Número 1 na Motivação exige que você se situe sempre de forma a ficar na frente dos outros. Tem que ser o (a) primeiro (a) em tudo o que faz. O fato de ser o (a) primeiro (a) o (a) impede, obviamente, de ter muita consideração pelos outros até que suas próprias necessidades sejam satisfeitas. A liderança adquirida em vidas passadas traz agora o desejo de continuar a se empenhar numa consciência mais elevada. Torna-se independente, também, com relação às suas crenças. O desejo por pensamentos livres e independentes continua ocupando o seu anseio mais profundo. Ambicioso (a) e criativo (a), é direto (a) e não gosta de muitos detalhes, quer liderar, dirigir, dominar; às vezes é obstinado (a). Não gosta muito de receber ordens de quem quer que seja e trabalha melhor por conta própria ou em cargo de chefia. A incompreensão e a recusa em aceitar conselhos podem trazer transtornos à sua carreira e aos seus planos profissionais. Se não tiver bom nível de consciência espiritual, poderá se tornar egoísta, excessivamente vaidoso (a) e arrogante. Geralmente é impaciente e com pouco senso diplomático. Por esse motivo poderá enfrentar dificuldades no seu meio profissional ou mesmo entre familiares, amigos e companheiros afetivos. Suas boas qualidades são: confiança em si, distinção, poder executivo, dignidade e foco nos propósitos.

Quando inseguro (a) tende a ameaçar os outros, podendo agredir, ofender, se tornar inflexível, irredutível, vingativo (a) e preconceituoso (a). Cultura, educação e refinamento pessoal são características indispensáveis que precisa adquirir para o seu triunfo pessoal, profissional e principalmente afetivo.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('motivacao', 2, 'Motivação 2', 'Deseja Paz e Equilíbrio – Prestar serviço e devoção; criar harmonia, sentir o ritmo da vida, trabalhar com os outros, ter amigos leais e boas companhias; acumular conhecimentos e coisas; conforto sem supérfluos; ser amado (a) por todos, receber convites, sentir-se compreendido (a); vencer todas as negociações; não ser exposto (a).

O Número 2 na Motivação indica o desejo de ser sempre gentil com todos, conseguindo ou não. Deseja ser compassivo (a), compreensivo (a), atencioso (a), útil e sempre fazendo concessões em favor da harmonia de todos. O seu maior desejo é a paz e a harmonia. O discernimento é um ponto forte do seu caráter; por esse motivo é um (a) bom (a) intermediário (a) ajudando a levar a paz às forças opostas. Anseia por amor e compreensão e prefere ser liderado (a) a liderar. O seu desejo é estar casado (a); desfrutar de companheirismo, paz, harmonia e conforto. Manifesta a sua natureza sensível através da suavidade, cordialidade e prestatividade; a sua principal característica é a cooperação. Pela sua passividade e calma natural, normalmente as pessoas com quem convive tendem a se aproveitar e explorá-lo (a). Normalmente não procura impor suas ideias; prefere escutar os outros antes de expor as suas próprias. Está sempre procurando reunir conhecimentos sobre assuntos diversos e se relaciona com todas as pessoas sem discriminar raça, credo, classe social ou posição econômica; numa só amizade e dedicação. É muito vulnerável em sua sensibilidade e se magoa profundamente com fatos que a outros não afetariam.

Quando inseguro (a) tende a não decidir, escapa, elogia demais os outros, deixa-se influenciar, chora, enfraquece, fica longe das atenções, se deprime, critica e ironiza. É importante para o seu desenvolvimento profissional e pessoal, que aprenda a conviver com as pessoas; ser mais comunicativo (a) e compartilhar os seus conhecimentos com todos, levando sua mensagem de harmonia e paz.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('motivacao', 9, 'Motivação 9', 'Deseja Entendimento Universal – Aconselhar e servir o mundo, ser o (a) guru; concluir as coisas; entender a lei suprema, melhorar as condições de tudo e de todos, de qualquer ser humano; amor impessoal e grande sedução; desprendimento e visão ampla; distância de raízes e detalhes; cultura geral e ter coisas belas; emoção forte e determinação; vida pessoal secundária em relação às outras pessoas; fama e sucesso, ser aceito (a), passar boa imagem de si; talento para suprir suas fantasias.

O Número 9 na Motivação representa o seu desejo de descobrir em todos algo com que possa se identificar. Quer ver a vida de uma perspectiva mais ampla e luta continuamente para enfatizar os vínculos que a humanidade tem em comum e não as diferenças que distinguem uns dos outros. Tem uma maneira peculiar de ver as coisas, o que o (a) leva facilmente ao fanatismo. A intuição é fortemente ativa; pode despertar outras percepções sobre a realidade não física. Sente necessidade de dar e receber amor. É gentil e clemente, de uma consciência expansiva dedicada à elevação da humanidade. Está no ápice da realização intelectual e espiritual. Busca sempre o conhecimento, e quer ensinar, aconselhar e servir à humanidade. Possui um saber autoconsciente que, se for desenvolvido, pode se revelar genial. Tem raciocínio rápido, vivo, ponderado e lógico para solucionar problemas que esteja enfrentando e os que eventualmente possa surgir. Gosta de ser elogiado (a), mas não espera por isso, pois normalmente suas ações são altruístas e desprovidas de interesse pessoal. Às vezes falta concentração e persistência, principalmente no campo profissional; com isso perde boa parte de suas fantásticas ideias. É corajoso (a) e destemido (a) diante do perigo e não tem medo da derrota, pois sabe se levantar com redobrada energia. A sua principal característica é o amor incondicional e a universalidade em seus sentimentos e visão. Consegue superar o egoísmo. Realiza-se na alegria que encontra nas mínimas coisas, na simpatia que sente por todos, na congruência de seus princípios e na contenção instintiva que acompanha tudo o que faz. Gosta de viagens e contatos no exterior; sente que todos os povos e raças são seus irmãos e quer conhecê-los e ser conhecido e amado por eles.

Quando inseguro (a) tende a usar os outros, sentir-se vítima, deixar as oportunidades passarem; alienar-se, dissimular, ficar apático (a), manipular as pessoas e se achar o próprio Deus ou iluminado (a) pelos espíritos; a deprimir-se. Precisa desenvolver as suas boas qualidades; do contrário poderá se tornar solitário (a) e introvertido (a), dominado (a) por seus conflitos íntimos e passível de incompreensão por si próprio, e daqueles que o (a) rodeiam.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

-- DESAFIOS (números 0-8)
INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('desafio', 0, 'Desafio 0', 'Pode escolher entre enfrentar todos os obstáculos que existem, ou não ter desafio algum a vencer. Seu Eu Superior saberá orientá-lo (a), pois a sua alma possui a inteligência do significado de todos os números, e conhece os meios de superar todas as fraquezas. O desafio zero indica ser uma alma que conserva latentes os conhecimentos trazidos de outros ciclos da existência. Pode também ser o mais penoso de todos os desafios para quem não cultiva o amor, a compreensão, o autoconhecimento. É o desafio da escolha. É provável que tenha dificuldade em agir conforme suas preferências. O desafio zero indica que poderá ser evoluído (a) para tomar suas próprias decisões. Deve atentar para todos os desafios sem uma ênfase especial em qualquer deles. Fique atento (a) para quais armadilhas a vida lhe reserva. Para encarar o desafio zero é preciso ter controle de todos os outros desafios: a independência do 1, a diplomacia do 2, o otimismo do 3, a aplicação do 4, a compreensão do 5, o ajuste e sincronia do 6, a sabedoria do 7, o poder construtivo do 8.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('desafio', 1, 'Desafio 1', 'Falta de iniciativa e dificuldade para decidir. Tendência para a solidão ou para a independência extrema. Precisa desenvolver a força de vontade, a coragem e o caráter, ou estará sujeito (a) a ser dominado (a) e mantido (a) em humildade diante dos outros, principalmente dos próprios parentes. Surgirão divergências, das quais deve se libertar, sem imputar culpa aos outros ou ressentir-se e se tornar beligerante. Pode se achar vacilante e voltar-se em todas as direções para agradar aos outros. Sofrerá a intromissão de estranhos e não agradará a ninguém nem a si próprio enquanto for fraco (a) e indeciso (a). Precisa persistir e se tornar determinado (a) a exigir respeito dos outros, respeitando-se, antes, a si mesmo (a). Precisa confiar em suas ideias criativas e originais. Deve avaliar seus planos antes de executá-los, assegurando-se de que são viáveis, plausíveis e racionais. Certo (a) e seguro (a) do que vai fazer, deve seguir em frente com firmeza e decisão.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('desafio', 3, 'Desafio 3', 'Tendência para o desperdício de energia e a falar em excesso, ou emudecer demais. Precisa aprender a não dispersar seus talentos, pois tende a fazer muitas coisas ao mesmo tempo. Aprenda a tolerar críticas, a enfrentá-las; cultive amigos e viva em sociedade, pois se temer as críticas poderá se tornar recluso (a). Precisa aprender a não ser extravagante impelido pelo desejo de ser diferente das outras pessoas. Evite falatórios e mexericos, pois sempre acabarão sendo atribuídos a si próprio (a), causando-lhe aborrecimentos. Não se deixe dominar pela melancolia ou autocomiseração, tais sentimentos são nocivos e destrutivos. Exponha seus talentos, pois assim estará proporcionando alegria a todos, melhorando o mundo e se realizando pessoalmente.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('desafio', 4, 'Desafio 4', 'Tendência para a falta de organização ou para o excesso de normas; para a preguiça ou preocupação excessiva com pouca coisa. Precisa aprender a disciplinar-se com relação a ser metódico (a), pontual e sistemático (a), para encontrar facilidade no seu progresso, desenvolvendo, assim, o grande senso de valores que possui. Deve evitar ser preguiçoso (a), teimoso (a) e dogmático (a), ou negligente com os detalhes e a não se importar com os compromissos ou encontros marcados. É prudente que procure dominar essas inclinações que são poderosos obstáculos ao seu progresso. Em geral, esse desafio mostra sua tendência para não gostar do trabalho e da poupança e, com frequência, a adiar o que tem a fazer ou fazê-lo de modo negligente. Está sujeito (a) a mudanças e inquietações constantes que criam uma tendência a se preocupar desnecessariamente. Para vencer esse desafio deve inspirar segurança e solidez. Persistindo na negatividade mostra irresponsabilidade e fecha as portas à sua frente. Terá sucesso se desenvolver o lado prático de sua natureza e confiar no seu raciocínio lógico.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

-- DESTINO (números 1-22)
INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('destino', 1, 'Destino 1', 'O Número 1 no Destino significa que a direção geral para a sua vida inteira será uma escalada sem fim para se superar ou para se aperfeiçoar a cada passo do caminho. Nada vem fácil demais para você. A totalidade de experiências da vida tende a empurrá-lo (a) de maneira que cada sucesso se transforme em mero fundamento para outro esforço em uma nova direção. A solução ideal para todas as situações importantes da vida com as quais você constantemente se defronta é confiar em seus próprios recursos, e nunca esperar que as soluções venham de outras pessoas. Seu destino consiste em desenvolver a sua individualidade, independência e capacidade de liderança. Às vezes você poderá ter de lutar contra as pressões para se conformar, mas realizará plenamente o seu potencial mantendo-se firme em suas convicções. Os outros o (a) procuram em busca de orientação. Deve reconhecer que precisa de colaboradores, embora a decisão final deva caber sempre a você. Seja o seu próprio chefe!

Pioneirismo, iniciativa, grande capacidade de liderança, inventividade, capacidade de comando e espírito executivo. Devido a estas características, com esta vibração, normalmente tem êxito e prosperidade em quase todas as atividades. Normalmente é firme nos ideais, constante nos desejos, ativo nos propósitos e fiel cumpridor de seus deveres, estando especialmente apto para ocupar postos de responsabilidade que requerem mente desperta e constantes iniciativas. O número 1 necessita de brilho, de reconhecimento e sucesso. Para conseguir esse estágio, dedica-se exaustivamente ao trabalho e normalmente torna-se o melhor na sua área de atuação. Dá sempre a impressão de ser feliz, ou estar feliz, mesmo que não esteja. A sua capacidade criativa por vezes se torna excesso de ânimo e surge naturalmente a arrogância, o caráter dominador e também certo egoísmo, pois tende a achar que o sucesso do grupo dependeu exclusivamente de seu esforço. Esse tipo de postura pode tornar difícil o convívio com os amigos e colegas de trabalho, além de dificultar o relacionamento a dois, pois não é nada fácil conviver com você. Como não gosta de receber ordens, é bom sempre procurar trabalhar por conta própria ou em cargo de chefia. É individualista, íntegro (a) e honesto (a) em seus propósitos e precisa aprender a ser pioneiro (a), a trabalhar em grupo e a ser o (a) comandante, não o (a) ditador (a); a ouvir conselhos, analisar situações e, após refletir, tomar decisões. Ou seja, não agir precipitadamente.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';

-- EXPRESSÃO - Adicionando textos completos
INSERT INTO numerology_texts (section, key_number, title, body, lang, version) VALUES 
('expressao', 8, 'Expressão 8', 'Você possui habilidade executiva e organizadora, senso de negócios e capacidade para lidar com grandes empreendimentos materiais. É eficiente, prático, determinado e possui visão ampla dos negócios. Tem capacidade natural para avaliar pessoas e situações em termos materiais. Possui ambição e luta pelo sucesso financeiro e reconhecimento. É um líder nato no mundo dos negócios, com talento para organizar, dirigir e comandar grandes grupos e empreendimentos. Sua expressão se manifesta através da busca pelo poder, prestígio e sucesso material. Tem facilidade para tomar decisões importantes e gerenciar recursos materiais de forma eficiente. É respeitado por sua competência profissional e capacidade de realização.

O número 8 na Expressão indica que você possui todas as qualidades necessárias para o sucesso no mundo material: visão de negócios, capacidade organizacional, determinação, eficiência e liderança. Sua missão é construir algo duradouro e significativo no plano material, sempre com ética e responsabilidade.', 'pt-BR', 'v2.0') ON CONFLICT (section, key_number) DO UPDATE SET body = EXCLUDED.body, version = 'v2.0';