// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbrhjptkfwugeheqmvlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicmhqcHRrZnd1Z2VoZXFtdmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0Mzk2NjUsImV4cCI6MjA3MzAxNTY2NX0.wSuo9CoiyVlUcwxd3wEz3aD5Sbhk91jiJfy47gmqj4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});